# ======================== PART - 1 ===========================

# Object Oriented Programming

In Oops, 3 important terms are used very frequently. They are<br><br>
1) Class<br>
2) Object<br>
3) Reference Variable<br><br>

Lets understand each of this terms in detail.<br><br>

**For example**, we want to build a 100 Floors building. To construct it we need to approach an architect for a plan. This plan is the blueprint for the builing i.e. it clearly describes no. of floors and no. of flats to each floor and it also contains measurements for rooms in a flat .... etc. So, The Complete information will be available in the Plan.<br><br>

Since Plan is ready we can start construction of the **builing(B1)**. We can also construct the other buildings **B1, B2, B3 .... etc** with same plan in some other places also.<br><br>

Since the plan is as a blueprint to construct many buildings, Plan acts as a <span style="color:dark orange">**Class**</span> and the physical existence of the plan is called an <span style="color:dark orange">**Object**</span>. Hence the buildings are the **objects**<br><br>

<span style="color:Green">**With One class**</span>(Plan/BluePrint) <span style="color:Green">**we can create many Objects**</span>(buildings).



Lets understand reference variable:<br><br>
Lets say, we want to buy one **Sony KD-65 Model TV**. Out of many such TV's **(Objects)** manufactured from a sony company with same specifications and design of Sony KD-65 Model **(Plan)**. We bought one TV. To Operate the Sony KD-65 Model TV, we need a device called **Remote**. This Remote is the Reference to operate the TV. Hence, this remote acts as a <span style="color:dark orange">**Reference Variable**</span>.<br><br>

<span style="color:Light Green">**By using the Reference Variable, we can perform the required operation on the Object**</span>

Lets say, Remote is lost somewhere and you bought one more remote for existing Sony KD-65 Model TV. After some days, you find the old remote which is lost. Now, you have two remotes for one device and both are working to operate one TV. So we have Two Reference Variables (Remotes) for One Object(Sony KD-65 Model TV).<br><br>

<span style="color:Green">**An object can have any number of reference variables.**</span><br>

## Class

### What is Class:
⚽ In Python every thing is an object. To create objects we required some Model or Plan or Blue print, which is nothing but class.<br> ⚽ We can write a class to represent properties (attributes) and actions (behaviour) of object.<br>
⚽ Properties can be represented by variables<br> ⚽ Actions can be represented by Methods.<br>
⚽ Hence class contains both variables and methods.<br>

### How to define a Class?
We can define a class by using class keyword.<br>
**Syntax:**<br><br> 
**class** className:<br>
&nbsp;&nbsp;&nbsp;&nbsp;    ''' documentation string '''<br> 
&nbsp;&nbsp;&nbsp;&nbsp;    **variables:** instance variables,static and local variables. Variables represent attributes/properties<br> 
&nbsp;&nbsp;&nbsp;&nbsp;    **methods:** instance methods,static methods,class methods. This represents actions/behaviours<br><br>

Documentation string represents description of the class. Within the class doc string is always optional. We can get doc string by using the following 2 ways.<br>
1) print(classname.\_\_doc\_\_) <br>
2) help(classname)<br><br>
Example:

In [2]:
class Student:
    '''This is the student class with required data'''
    # variables
    # methods
print(Student.__doc__)
help(Student)

This is the student class with required data
Help on class Student in module __main__:

class Student(builtins.object)
 |  This is the student class with required data
 |  
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



Within the Python class we can represent data by using variables.<br><br>
There are 3 types of variables are allowed.<br><br>
> **1) Instance Variables (Object Level Variables)<br> 
> 2) Static Variables (Class Level Variables)<br> 
> 3) Local variables (Method Level Variables)**

Within the Python class, we can represent operations by using methods. The following are various types of allowed methods
> **1) Instance Methods<br>
> 2) Class Methods<br>
> 3) Static Methods**

Example for Class:

In [4]:
class Student:
    '''This is the demonstration of class with variables and methods'''
    def __init__(self): #we will discuss about __init__ further
        self.name = "Sairam" #variable1
        self.rollno = 101 #variable2
        self.marks = 90 #variable3
    
    def talk(self): # method1
        print("Hello I am ",self.name)
        print("My Rollno is ",self.rollno)
        print("My marks are ",self.marks)
        
s = Student() # s is the Reference Variable of the Object/class Student
print(s.name) # With Reference vaiable we can access the propeties of the an object/class
print(s.rollno)
print(s.marks)
s.talk() # Reference variable can also access the methods defined in the Class

Sairam
101
90
Hello I am  Sairam
My Rollno is  101
My marks are  90


### What is Object: 
Pysical existence of a class is nothing but object. We can create any number of objects for a class.<br>
**Syntax to Create Object:<span style="color:green"> referencevariable = classname()**</span><br>
**Example:** s = Student()

### What is Reference Variable? 
The variable which can be used to refer object is called reference variable. By using reference variable, we can access properties and methods of object.<br><br>
**Program:** Write a Python program to create a Student class and Creates an object to it. Call the method talk() to display student details

In [5]:
class Student:
    '''This is the demonstration of class with variables and methods. 
    For evry student, name, roll no, marks will varied. So, we method should be dynamic as follows'''
    #Since variables will be vary for every student. we should be able to get the variables from user
    def __init__(self,name,rollno,marks): 
        self.name = name # 
        self.rollno = rollno #variable2
        self.marks = marks #variable3
    
    def talk(self): 
        print("Hello I am ",self.name)
        print("My Rollno is ",self.rollno)
        print("My marks are ",self.marks)
        
s1 = Student("Sunny",101,90) # This parameters will be passed to __init__ method arguments.

# Since, we made it dynamic. We can create n number of objects like below.

s2 = Student("Katrina",102,95)
s1.talk() # Student object will be called with a reference variable s1 and talk() method will be executed with the parameters passed from the s1.  
print("*"*50)
s2.talk() # Student object will be called with a reference variable s2 and talk() method will be executed with the parameters passed from the s2.

Hello I am  Sunny
My Rollno is  101
My marks are  90
**************************************************
Hello I am  Katrina
My Rollno is  102
My marks are  95


# Complete Understanding of "self" variable 

# Self Variable: 

 - **self** is the default reference variable which is always pointing to current object.<br>
 - By using **self** we can access instance variables and instance methods of object.<br>

**Note:**<br>
1) self should be first parameter inside constructor<br>
>    def **\_\_init\_\_**(self):<br>

2) self should be first parameter inside instance methods.<br>
> def talk(self):

In [1]:
class Test:
    def __init__(self):
        pass

t=Test() # t is the reference variable for Test Object, can be used only outside of the class.
    

We cannot use **t** within the class, since it is declared outside the class. Within the class to use this current object some reference variable must be required, that reference variable is nothing but "**self**".<br>
<br>Now Both **t** and **self** pointing to same object. Lets see the example below for proof<br>
![Image](images/self.png)

In [2]:
class Test:
    def __init__(self):
        print("Address of object pointed by self :",id(self))

t=Test() # t is the reference variable for Test Object, can be used only outside of the class.
print("Address of object pointed by 't' :",id(t))    

Address of object pointed by self : 1752463999520
Address of object pointed by 't' : 1752463999520


If we observe, both **t** and **self** are pointing to same address of the object.<br>
Hence, we can say<br>
> **t** should be used as a reference variable outside the object.<br>
> **self** is reference variable pointing to current object, we should use self within the python class to refer current object.

In [4]:
class Test:
    def __init__(self):
        print("Constructor")
    
    def m1(self,x):
        print('x value :',x)  
        
t=Test()
t.m1(10) # we are passing only one value for x. Python takes responsibility to provide the value for self internally.

Constructor
x value : 10


**Note:** whenever we are calling a method, we are not required to provide a value for the self variable, internally python virtual machine is responsible to provide a value for self.

In [5]:
class Student:
    
    def __init__(self,name,rollno,marks): 
        self.name = name # 
        self.rollno = rollno #variable2
        self.marks = marks #variable3
    
    def talk(self): 
        print("Hello I am ",self.name)
        print("My Rollno is ",self.rollno)
        print("My marks are ",self.marks)
        
s1 = Student("Sairam","14911A263",100)

Whenever an object is called constructor will be executed.<br>
we have passed "name = Sairam", "rollno = 14911A0263", "marks = 100".<br>
We have not passed any value for self because python itself is responsible for that. Internally self is used as follows:<br><br>

1) Whenever we are creating an object lets say **s1** is created, automatically constuctor is executed.<br>
2) within the constructor, **self.name** means **current object name variable**. So a name variable is created in the current object and for this name variable we are assigning the value of this name which is passed as "Sairam" from s1.<br>
3) Similiarly **rollno** and **marks** variables will be created for current object s1 with the passed values "14911A0263" and "100". <br><br>
![Image](images/instance_variables.png)

 - The First purpose we are using **self** variable in the constuctor is to declare **instance variables**<br>
 - The Second Pupose we are using **self** is to access the instance variables created for the using them in methods or some other places. **For example**: instance variables **self.name**, **self.rollno**, **self.marks** will be used in talk method<br>



In [6]:
s1.talk() # all the instance variables created for s1 object will be used in talk() method to display the below output.

Hello I am  Sairam
My Rollno is  14911A263
My marks are  100


**is self a keyword in python ?**<br><br>
 - self is not a keyword in python, we can use any other words inplace of self. But it is not recommended universally, so restricting to self is best.<br>
 - Even if we use other words like delf,kelf etc in place of self this will work fine.<br>
 - **The first argument whatever you are using is implicit variable pointing towards current object**, so any name can be used in place of first argument instead of self, it will work fine as shown below.<br><br>
 
**Note:** using **self** as first argument is recommended universally instead of other names.

In [1]:
class Student:
    
    def __init__(delf,name,rollno,marks): # self replaced with delf
        delf.name = name # 
        delf.rollno = rollno #variable2
        delf.marks = marks #variable3
    
    def talk(kelf): # using kelf as first argument instead of self
        print("Hello I am ",kelf.name)
        print("My Rollno is ",kelf.rollno)
        print("My marks are ",kelf.marks)
        
s1 = Student("Sairam","14911A263",100)
s1.talk()

Hello I am  Sairam
My Rollno is  14911A263
My marks are  100


**What if we don't give self argument ?**

In [2]:
class Student:
    
    def __init__(name,rollno,marks): # if we don't give self argument, whatever first argument avaialble is considered as self.
        delf.name = name  
        delf.rollno = rollno 
        delf.marks = marks 
    
    def talk(kelf): # using kelf as first argument instead of self
        print("Hello I am ",kelf.name)
        print("My Rollno is ",kelf.rollno)
        print("My marks are ",kelf.marks)
        
s1 = Student("Sairam","14911A263",100)
s1.talk()

TypeError: __init__() takes 3 positional arguments but 4 were given

name is considered as self, remaining two arguments are normal arguments. In s1 we are passing one extra parameter to the \_\_init\_\_. Hence, Type error will be raised.

#### self Variable conclusions

1) Within the python class to refer current object,some variable must be required which is nothing but **self**.<br>
2) self is the reference variable pointing to the current object.<br>
3) The first argument to the constructor and instance methods is self.<br>
4) At the time of calling the constructor or instance method we are not required to pass any value to self variable. Internally PVM is responsible to provide variable.<br>
5) The main purpose of self variable within the class is to declare instance variables and to access the values of instance variables.<br>
6) self is not a keyword instead of 'self' we can use any name like delf, kelf etc. but it is recommended to use **self** only.<br>
7) We can use self from outside the class.<br>

## The Complete Story of Python Constructors

#### Constructor Concept:

☕ Constructor is a special method in python.<br> ☕ The name of the constructor should be **\_\_init\_\_(self)**<br> ☕ Constructor will be executed automatically at the time of object creation.<br> ☕ The main purpose of constructor is to declare and initialize instance variables.<br> ☕ Per object constructor will be exeucted only once. if we are creating 3 objects, constructor will be executed 3 times.
<br> ☕ Constructor can take atleast one argument(atleast self)<br> ☕ Constructor is optional and if we are not providing any constructor then python will provide default constructor.

In [8]:
class Test:
    def __init__(self):
        print("Constructor Execution....")
t1=Test() # constructor is executed only one time because only one object has created.

Constructor Execution....


In [9]:
t1=Test()
t2=Test()
t3=Test()

# This will execute constructor 3 times

Constructor Execution....
Constructor Execution....
Constructor Execution....


In [12]:
# The main purpose of constructor is to declare and initialize instance variables.

class Student:
    
    def __init__(self,name,rollno,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  
        self.rollno = rollno 
        self.marks = marks
        
s1 = Student('Sunny',121,95) # All the Instance variables for the object s1 will be created using constructor.
print(s1.name,s1.rollno,s1.marks)
s2 = Student("Sairam",122,96) # All the Instance variables for the object s2 will be created using constructor.
print(s2.name,s2.rollno,s2.marks)

Creating instane variables and performing initialization...
Sunny 121 95
Creating instane variables and performing initialization...
Sairam 122 96


**Within Pyhton class constructor is always optional, if we are not providing any constructor then python will provide default constructor.**

In [18]:
# Lets say we are not creating any constructor method in python class. lets see will it execute or not

class Test:
    
    def m1(self):
        print("Method Executed without Constructor in class")
t = Test()
t.m1()

Method Executed without Constructor in class


without creating any constructor method within python class, the Test class is executed. It is because, python has provided default constuctor.

In [14]:
class Test:
    
    def __init__(self):
        print("Constructor Execution")
        
t = Test() # this will execute a constructor method because we are creating an object t.
t.__init__() # if we call a constructor explicitly,new object won't be created, it will be executed just like a normal method
t.__init__() # if we call a constructor explicitly,new object won't be created, it will be executed just like a normal method

# Total 3 times construction execution will be done

Constructor Execution
Constructor Execution
Constructor Execution


At the time of creating an object constructor method will be called automatically. If we call a constructor explicitly outside the class, new object won't be created, it will be executed just like a normal method as shown above.

Two constuctor Methods with same name and different arguments will not support in python i.e. Overloading is not supported in python. Lets see the below example

In [16]:
class Test:
    
    def __init__(self):
        print("No-argument constructor")
        
    def __init__(self,x): # only Latest Constructor method will be considered, even if we provide two constructor methods
        print("One-Argument Constructor")
        
t1 = Test()

TypeError: __init__() missing 1 required positional argument: 'x'

We got error because, it has considered the latest constructor method which should be passed x value. we didn't passed any x value to t1. hence the error. Lets check t2 = Test(10)

In [17]:
t2 = Test(10) # This worked fine.

One-Argument Constructor


### Constructor Conclusions

**1)** Constructor is a special method in python.<br>
**2)** The name of the Constructor is always \_\_init\_\_()<br>
**3)** We are not required to call constructor explicitly. Whenever we are creating an object, automatically constructor will be executed.<br>
**4)** Per object constructor will be exeucted only once. if we are creating 3 objects, constructor will be executed 3 times.<br>
**5)** The main purpose of constructor is to declare and initialize instance variables.<br>
**6)** Constructor can take atleast one argument(atleast self)<br>
**7)** within the class, Constructor is optional and if we are not providing any constructor then python will provide default constructor.<br>
**8)** Based on our requirement we can call constructor explictly, then it will be executed just like a normal method.<br>
**9)** Overloading Concept is not applicable for constructors. Hence we cannot define multiple constructors within the same class. If we are trying to define multiple constructors, only the latest constructor will be considered.



### A small Application to explain OOP 

**Write a program to add movie name,hero,heroine name to temporary memory like list by taking input from user and finally display all the movies listed in the memory.**

In [6]:
class Movie:
    '''This Movie class to get title, ero, heroine of the movie '''
    def __init__(self,title,hero,heroine):
        self.title = title
        self.hero = hero
        self.heroine = heroine
        
    def info(self):
        print("Movie Name : ",self.title)
        print("Hero Name : ",self.hero)
        print("Heroine Name : ",self.heroine)

list_of_movies = []
while True:
    title = input('Enter Movie Name: ')
    hero = input('Enter Hero Name: ')
    heroine = input('Enter Heroine Name: ')
    m=Movie(title,hero,heroine)
    list_of_movies.append(m)
    print('Movie added Successfully...')
    print()
    option = input('Do you want to add one more movie [yes/no]: ')
    print()
    if option.lower()=='no':
        break
        
print('All Movies Information....')
print()
for movie in list_of_movies:
    movie.info()
    print()

Enter Movie Name: Bahubali
Enter Hero Name: Prabhas
Enter Heroine Name: Anushka
Movie added Successfully...

Do you want to add one more movie [yes/no]: yes

Enter Movie Name: Temper
Enter Hero Name: NTR
Enter Heroine Name: Kajal Agarwal
Movie added Successfully...

Do you want to add one more movie [yes/no]: no

All Movies Information....

Movie Name :  Bahubali
Hero Name :  Prabhas
Heroine Name :  Anushka

Movie Name :  Temper
Hero Name :  NTR
Heroine Name :  Kajal Agarwal



<img src = "images/method_vs_constructor.png" width=800>

**What happens if we provide method name same as class name**

In [7]:
class Test:
    def Test(self):
        print('Method')
t = Test() # This will execute the default constructor automatically
t.Test() # Test method inside class Test will be executed.

Method


Yes, we can give method name same as class name, tough it is legal,but it is not recommended.

# Understanding Eveything in Types of variables - Instance, Static and Local 

#### Types of Variables:

Inside Python class 3 types of variables are allowed.<br>
> 1) Instance Variables (Object Level Variables)<br>
> 2) Static Variables (Class Level Variables)<br>
> 3) Local variables (Method Level Variables)

## 1) Instance Variables:
 - If the value of a variable is varied from object to object, then such type of variables are called instance variables or object level variables.<br>
> **Example:** **name**,**rollno** and **marks** of the student 
![Image](images/instance.png)
 - For every object a separate copy of instance variables will be created.<br>
 - Most of the times instance variables will be declared inside the constructor by using self variable. 
 
**Where we can declare Instance Variables:**<br>
> 1) Inside Constructor by using self variable<br>
> 2) Inside Instance Method by using self variable<br>
> 3) Outside of the class by using object reference variable

### 1) Inside Constructor by using Self Variable: <br><br>
We can declare instance variables inside a constructor by using self keyword. Once we creates object, automatically these variables will be added to the object.

In [2]:
class Student:
    
    def __init__(self,name,rollno,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  
        self.rollno = rollno 
        self.marks = marks

# For student object from s1,s2, ...... ,s200, instance variables will be created
# and values will be assigned upon calling Student Class with required parameters.         

s1 = Student('Sairam',1,100) 
s2 = Student("Dhana",2,95)
# .......
# .......
# .......
s200 = Student("Prasad",200,100)


Creating instane variables and performing initialization...
Creating instane variables and performing initialization...
Creating instane variables and performing initialization...


In [3]:
print(s1.name,s1.rollno,s1.marks)
print(s2.name,s2.rollno,s2.marks)
print(s200.name,s200.rollno,s200.marks)

Sairam 1 100
Dhana 2 95
Prasad 200 100


In [6]:
# we can get the no. of instance variables of an object with "object.__dict__" as follows
print(s1.__dict__)
print(s2.__dict__)
print(s200.__dict__)

{'name': 'Sairam', 'rollno': 1, 'marks': 100}
{'name': 'Dhana', 'rollno': 2, 'marks': 95}
{'name': 'Prasad', 'rollno': 200, 'marks': 100}


### 2) Inside Instance Method by using self variable

 - We can also declare instance variables inside instance method by using self variable.<br>
 - If any instance variable declared inside instance method, that instance variable will be added once we call that method.<br>
 - If we are not calling the Instance method then those variables won't be added to the object.

In [7]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        
    def m1(self): 
        self.c = 30 # declaring Instance variable inside the method, this variable will be execute only if it is called explicitly
        
t = Test() # Only the constructor method will be called automatically
print(t.__dict__)

{'a': 10, 'b': 20}


Tough we have declared Instance Variable inside the method, it will not execute and show up in the Instance variables dict. It is because, we haven't called the method m1.<br><br> upon calling the m1() method, self.c will be added to Instance variable dict as follows.

In [8]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        
    def m1(self): 
        self.c = 30 # this will be executed and added to the instance variables dict upon calling the method 
        
t = Test() # Only the constructor method will be called automatically
t.m1() # all the instance variables declared inside a method will be executed and adds to the instance variables dict on calling the method
print(t.__dict__)

{'a': 10, 'b': 20, 'c': 30}


Since we have called the method m1, Instance variable dict has resulted 3 instance variables.

### 3) Outside of the Class by using Object Reference Variable:

We can also add instance variables outside of a class to a particular object.

In [10]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        
    def m1(self): 
        self.c = 30 
        
t = Test() # a,b will be added to the object 
t.m1() # c will be added to the object 
t.d = 40 # d will be added to the object, this Instance variable is declared outside the class
print(t.__dict__) # hence a,b,c,d will be resulted in Instance Variables dict as follows

{'a': 10, 'b': 20, 'c': 30, 'd': 40}


In [11]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        
    def m1(self): 
        self.c = 30 
        
t1 = Test() # a,b will be added to the object automatically upon creating an object. 
t1.m1() # c will be added to the object from inside the Instance Method only upon calling the method m1.
t1.d = 40 # d will be added to the object from outside of the class using object reference variable.
t2 = Test()
print(t1.__dict__) # a,b,c,d will be added to the object t1
print(t2.__dict__) # only a,b will be added to the object t2

{'a': 10, 'b': 20, 'c': 30, 'd': 40}
{'a': 10, 'b': 20}


From above example we can see that, **Number Instance Variables will vary from object to object** 

### How to Access Instance Variables: 

We can access instance variables with in the class by using **self** variable and outside of the class by using **object reference**.

In [14]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        
    def display(self): 
        print(self.a) # Accessing the Instance Variable a from constructor and printing it 
        print(self.b) # Accessing the Instance Variable b from constructor and printing it
        
t = Test()
t.display()
print(t.a) # Accessing value of a using object reference
print(t.b) # Accessing value of b using object reference

10
20
10
20


### How to delete Instance Variable from the Object:

1) Within a class we can delete instance variable as follows: <br>
> **del self.variableName**<br>
> Example : <span Style="color:orange">del self.a</span>

2) From outside of class we can delete instance variables as follows: <br> 
> **del objectreference.variableName**<br>
> Example: <span Style="color:orange">del t2.b, t2.d</span>

In [16]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        self.c = 30
        self.d = 40
        
    def m1(self): 
        del self.c # deleting the Instance Variable within the class upon calling the method
        
t1 = Test()
print("Values Before calling m1 method : ",t1.__dict__) # All Instance Variables will present
t1.m1() # Upon calling m1() Instance Variable c will be deleted
print("Values After Calling m1 method : ",t1.__dict__) # All Instance Variables after deleting Instance Variable c

Values Before calling m1 method :  {'a': 10, 'b': 20, 'c': 30, 'd': 40}
Values After Calling m1 method :  {'a': 10, 'b': 20, 'd': 40}


In [19]:
t2 = Test()
print("Values Before deleting Instance Variables Outside the Class : ",t2.__dict__) # All Instance Variables will present
del t2.b,t2.d
print("Values After deleting Instance Variables Outside the Class : ",t2.__dict__)

Values Before deleting Instance Variables Outside the Class :  {'a': 10, 'b': 20, 'c': 30, 'd': 40}
Values After deleting Instance Variables Outside the Class :  {'a': 10, 'c': 30}


**Note:** The instance variables which are deleted from one object,will not be deleted from other objects.

### Updating Instance Variables of an Object:

If we change the values of instance variables of one object then those changes won't be reflected to the remaining objects, because for every object we are separate copy of instance variables are available.

In [21]:
class Test:
    
    def __init__(self):
        self.a = 10
        self.b = 20
        
t1 = Test()
print("values of Instance Variables of object t1 before Updating are:",t1.__dict__)
t1.a = 888
t1.b = 999
print("values of Instance Variables of object t1 After Updating are:",t1.__dict__)
t2 = Test()
print("values of Instance Variables of object t1 After Updating in t1 will not change in t2:" ,t2.__dict__)

values of Instance Variables of object t1 before Updating are: {'a': 10, 'b': 20}
values of Instance Variables of object t1 After Updating are: {'a': 888, 'b': 999}
values of Instance Variables of object t1 After Updating in t1 will not change in t2: {'a': 10, 'b': 20}


In [26]:
print("t1.a = {}, t1.b = {} ".format(t1.a,t1.b))
print("t2.a = {}, t2.b = {} ".format(t2.a,t2.b))

t1.a = 888, t1.b = 999 
t2.a = 10, t2.b = 20 


## 2) Static Variables

☕ If the value of a variable is not varied from object to object,then it is not recommended to declare those variables as instance variables. we have to declare with in the class directly but outside of methods. Such types of variables are called Static variables.<br>
> **Example**: College Name of the student will be same for all the 200 students.
![Image](images/static-variable.png)

☕ In the case of instance variables, for every object a seperate copy will be created. In case of static variables, only one copy will be created and shared by all objects of that class.<br>
☕ Most of the times, static variables should be declared within the class directly<br>
☕ We can access static variables either by class name or by object reference. But recommended to use class name.
<br><br>
#### Instance Variable vs Static Variable:
**Note:** In the case of instance variables for every object a seperate copy will be created,but in the case of static variables for total class only one copy will be created and shared by every object of that class.

In [7]:
class Student:
    
    college_name = 'VJIT' # Static Variable
    def __init__(self,name,rollno,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  # Instance Variable
        self.rollno = rollno # Instance Variable
        self.marks = marks # Instance Variable

# For student object from s1,s2, ...... ,s200, instance variables will be created
# and values will be assigned upon calling Student Class with required parameters.         

s1 = Student('Sairam',1,100) 
s2 = Student("Dhana",2,95)
# .......
# .......
# .......
s200 = Student("Prasad",200,100)

Creating instane variables and performing initialization...
Creating instane variables and performing initialization...
Creating instane variables and performing initialization...


### Various Places to declare Static Variables:
1) In general we can declare within the class directly but from out side of any method<br>
2) Inside constructor by using class name<br>
3) Inside instance method by using class name<br>
4) Inside classmethod by using either class name or cls variable<br>
5) Inside static method by using class name<br>
6) Outside of class by using Class Name.

In [1]:
class Test:
    a = 10 # 1) declaring within the class directly but from outside of any method
    def __init__(self):
        Test.b = 20 # 2) Declaring Inside constructor by using class name, This will be executed at time of object creation.
    def m1(self):
        Test.c = 30 # 3) Declaring Inside Instance Method using class name, this method has to be called other wise it will not add to the class.

In [2]:
print(Test.__dict__) # Only a = 10 is available in the class dict. since only Test class is called.

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000017E601671F0>, 'm1': <function Test.m1 at 0x0000017E60167C10>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}


In [4]:
# To add b to the dict, we need to create an object. constructor will be called automatically and b = 20 will be added to dict.
t = Test()
print(Test.__dict__) # Now a=10 and b=20, both will be added to the class dict.

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000017E601671F0>, 'm1': <function Test.m1 at 0x0000017E60167C10>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None, 'b': 20}


In [5]:
# We have to call the the Instance Method, otherwise static variable won't be added to the class.
t.m1()
print(Test.__dict__) # Now a=10,b=20,c=30 all three will be added to class Test.

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000017E601671F0>, 'm1': <function Test.m1 at 0x0000017E60167C10>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None, 'b': 20, 'c': 30}


In [12]:
class Test:
    a = 10 # 1) declaring within the class directly but from outside of any method
    def __init__(self):
        Test.b = 20 # 2) Declaring Inside constructor by using class name, This will be executed at time of object creation.
    def m1(self):
        Test.c = 30 # 3) Declaring Inside Instance Method using class name, this method has to be called other wise it will not add to the class.
    
    @classmethod
    def m2(cls):
        cls.d=40 # 4) We can declare static variables Inside Class Method either by using cls or class name i.e d=40 using cls
        Test.e=50 # 4) We can declare static variables Inside Class Method either by using cls or class name i.e e=50 using class name Test
        
    @staticmethod
    def m3():
        Test.f = 60 # 5) declaring Inside static method by using class name
print(Test.__dict__)
print()
t=Test()
print(Test.__dict__)
print()
t.m1()
print(Test.__dict__)
print()
Test.m2() # calling the m2 to add d=40 and e=50 to the class.
print(Test.__dict__)
print()
Test.m3() # # calling the m2 to add f=60 to the class.
print(Test.__dict__)
print()
Test.g = 70 # 6) declaring static variable Outside of class by using Class Name
print(Test.__dict__) # all the static variables which are declared in various places inside class will be executed and will be added to the class Test.

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000017E602459D0>, 'm1': <function Test.m1 at 0x0000017E60245940>, 'm2': <classmethod object at 0x0000017E602580D0>, 'm3': <staticmethod object at 0x0000017E60258100>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000017E602459D0>, 'm1': <function Test.m1 at 0x0000017E60245940>, 'm2': <classmethod object at 0x0000017E602580D0>, 'm3': <staticmethod object at 0x0000017E60258100>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None, 'b': 20}

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000017E602459D0>, 'm1': <function Test.m1 at 0x0000017E60245940>, 'm2': <classmethod object at 0x0000017E602580D0>, 'm3': <staticmethod object at 0x0000017E602

### How to access Static Variables:

1) **inside constructor**: by using either self or classname<br>
2) **inside instance method**: by using either self or classname<br>
3) **inside class method**: by using either cls variable or classname<br>
4) **inside static method**: by using classname <br>
5) **From outside of class**: by using either object reference or classname

In [13]:
class Test:
    a=10
    def __init__(self):
        print(self.a) # 1) Accessing Static Variable with Self inside Constructor
        print(Test.a) # 1) Accessing Static Variable with Class name(Test) inside Constructor

t=Test() # Both will be printed with same value.


10
10


In [21]:
class Test:
    a=10
    def __init__(self):
        print("1) Accessing Static Variable with Self inside Constructor :",self.a) # 1) Accessing Static Variable with Self inside Constructor
        print("1) Accessing Static Variable with Class name(Test) inside Constructor :",Test.a) # 1) Accessing Static Variable with Class name(Test) inside Constructor
        print()
        
    def m1(self):
        print("2) Accessing Static Variable with Self inside Class Method : ",self.a) # 2) Accessing Static Variable with Self inside Class Method
        print("2) Accessing Static Variable with Class name(Test) inside Class Method : ",Test.a) # 2) Accessing Static Variable with Class name(Test) inside Class Method
        print()
        
    @classmethod
    def m2(cls):
        print("3) Accessing the Static Variable using cls variable inside class method : ",cls.a)
        print("3) Accessing the Static Variable using class name inside class method : ",Test.a)
        print()
        
    @staticmethod
    def m3():
        print("4) Accessing The Static Variable inside Static Method using class name",Test.a)
        print()
        
t=Test() # Both will be printed with same value.
t.m1()
t.m2()
t.m3()
print("5) Accessing the Static Variable outside of class using object reference",t.a)
print("5) Accessing the Static Variable outside of class using Class Name",Test.a)


1) Accessing Static Variable with Self inside Constructor : 10
1) Accessing Static Variable with Class name(Test) inside Constructor : 10

2) Accessing Static Variable with Self inside Class Method :  10
2) Accessing Static Variable with Class name(Test) inside Class Method :  10

3) Accessing the Static Variable using cls variable inside class method :  10
3) Accessing the Static Variable using class name inside class method :  10

4) Accessing The Static Variable inside Static Method using class name 10

5) Accessing the Static Variable outside of class using object reference 10
5) Accessing the Static Variable outside of class using Class Name 10


### Where we can modify the Value of Static Variable: 
Anywhere either with in the class or outside of class we can modify by using classname. But inside class method, by using cls variable.<br><br>
**Note:** We cannot modify static variable value using self or object reference

In [23]:
class Test:
    a=10
    
print(Test.a) #This has to print the static variable value in class Test i.e a=10        

10


In [25]:
class Test:
    a=10
    def __init__(self):
        Test.a = 20 #on creating the object, this should update the value of 'a'

t=Test()
print(Test.a) #This has to print the Updated static variable value from the constructor i.e a=20        

20


In [26]:
class Test:
    a=10
    def __init__(self):
        print("Value Before Updating the Static Variable inside constructor using class name: ",Test.a)
        Test.a = 20
        print("Value After Updating the Static Variable inside constructor using class name: ",Test.a)
        print()
        
    def m1(self):
        Test.a = 30
        print("Value After Updating the Static Variable inside Instance Method using class name: ",Test.a)
        print()

    @classmethod
    def m2(cls):
        cls.a = 40
        print("Value After Updating the Static Variable inside class Method using class variable: ",Test.a)
        Test.a = 50
        print("Value After Updating the Static Variable inside class Method using class Name: ",Test.a)
        print()
        
    @staticmethod
    def m3():
        Test.a = 60
        print("Value After Updating the Static Variable inside Static Method using class Name: ",Test.a)
        print()
        
t= Test()
t.m1()
Test.m2()
Test.m3()
Test.a = 70
print("Value After Updating the Static Variable outside of class object using class Name: ",Test.a)

Value Before Updating the Static Variable inside constructor using class name:  10
Value After Updating the Static Variable inside constructor using class name:  20

Value After Updating the Static Variable inside Instance Method using class name:  30

Value After Updating the Static Variable inside class Method using class variable:  40
Value After Updating the Static Variable inside class Method using class Name:  50

Value After Updating the Static Variable inside Static Method using class Name:  60

Value After Updating the Static Variable outside of class object using class Name:  70


## Example Programs for Instance and Static Variables

### If we change the Value of Static Variable by using either self OR Object Reference Variable:

If we change the value of static variable by using either self or object reference variable, then the value of static variable won't be changed, just a new instance variable with that name will be added to that particular object.

In [2]:
class Test:
    a = 10
    def __init__(self):
        self.a = 888 # trying to change the static variable value of 'a' using self, this will only create a create new instance variable.
        
t1 = Test()
print(Test.a)
print(t1.a) # For Object Reference, Instance Variable is the first priority, if it is not available then it will consider static variable.
# since Instance Variable is created, a will result 888.

10
888


In [3]:
class Test:
    a = 10
    def m1(self):
        Test.a = 888 # on calling this method, this will update the static variable 'a' value to 888.
        #since we are updating using class name 'Test.a' 
        
t1 = Test()
t1.m1() # a=10 will be updated with a=888 upon calling m1 method since we are using class name ' Test' for updating the static variable value.
print(Test.a) # since the variable is updated at class level, this will result 888
print(t1.a) # Since Instance Variable is Not Available in Test class, as a second priority static variable value will be preferred i.e a=888

888
888


In [4]:
class Test:
    a=10 # Static Variable
    def __init__(self):
        self.b = 20 # Instance Variable
        
t1=Test() 
t2=Test()
print('t1:',t1.a,t1.b) # static Variable is Second piority of Object Reference if Instance Variable is Not Available hence t1.a = 10 
# and Instance Variable b is readily available hence t1.b = 20 will be displayed
print('t2:',t2.a,t2.b) # same as above
t1.a = 888 # we can't modify the static variable with object reference, so new instance variable will be created hence t1.a = 888 will be created
t1.b = 999 # Since Instance Variable 'b' is already available, this will modify the value of Instance Variable b from 20 to 999. 
print('t1:',t1.a,t1.b) # This will result t1.a = 888, t1.b = 999
print('t2:',t2.a,t2.b) # This will result t1.a = 10, t1.b = 20

t1: 10 20
t2: 10 20
t1: 888 999
t2: 10 20


**Important Conclusion:**<br>

<span style='color:green'>**If we are trying to change the value of static variable by using self (or) object reference variable, then the value of the static variable won't be changed, just a new instance variable with that name will be added to that particular object.**</span>    

In [5]:
class Test:
    a=10 # Static Variable
    def __init__(self):
        self.b = 20 # Instance Variable
        
t1=Test() 
t2=Test()

print('t1:',t1.a,t1.b) # static Variable is Second piority of Object Reference if Instance Variable is Not Available hence t1.a = 10 
# and Instance Variable b is readily available hence t1.b = 20 will be displayed

print('t2:',t2.a,t2.b) # same as above

Test.a = 888 # We are modifying the Static Variable at class level from outside of the class, so a= 10 will be replaced with 888 
Test.b = 999 # Since Static Variable 'b' is Not available at class level, this will create new Static Variable b with value 999. 

print('t1:',t1.a,t1.b) # This will result t1.a = 888, t1.b = 20
# Instance Variable a is not available in Test Class, hence Static variable t1.a = 888 will be preferred and instance variable b is
# readily available hence t1.b will be 20

print('t2:',t2.a,t2.b) # This will result t1.a = 888, t1.b = 20; Same as above


print('Test: ',Test.a,Test.b) # This will result Test.a = 888, Test.b = 999
# At class level, both Static variables a and b are available 

t1: 10 20
t2: 10 20
t1: 888 20
t2: 888 20
Test:  888 999


In [6]:
class Test:
    a=10
    def __init__(self):
        self.b = 20

t1=Test()
t2=Test()
Test.a = 888 # Static Variable 'a=10' will be replaced with 888.
t1.b = 999 # Instance Variable 'b=20' of object t1 will be replaced with 999
print("t1:",t1.a,t1.b) # Since Instance Variable a not availble, hence static variable a=888 will be considered.
# t1.b is already modified with 999, hence 999 will be displayed

print("t2:",t2.a,t2.b) # Static variable a = 888 will be displayed and Instance Variable b=20 of t2 object is already available without any update.


t1: 888 999
t2: 888 20


**As Seen Above**<br>

<span style='color:Green'>**If we perform any change to instance variable in an object, that change won't reflect in other objects.**</span><br>
> i.e in object t1 b=20 will be replaced with 999, whereas in t2 its still 20 since changes made in t1 Instance Variables didn't reflected in t2.

<span style='color:Green'>**If we perform any change to Static variable, that change will reflect in all objects.**</span><br>
> i.e Test Class a=10 is be replaced with 888, and that change at class level is reflected in t1 and  t2 with value 888 of static variable 'a'


In [7]:
class Test:
    a=10
    def __init__(self):
        self.b = 20
        
    def m1(self):
        self.a=888
        self.b=999
        
t1=Test() # on calling this Static Variable a =10 and Instance Variable b=20 are available
t2=Test() # on calling this Static Variable a =10 and Instance Variable b=20 are available
t1.m1() # on calling this method m1, Instance Variable a=888 will created in t1 and b=20 will be replaced with 999 in t1
print("t1: ",t1.a,t1.b) #Since both the instance variables are available in t1 i.e a=888,b=999 will be displayed 
print("t2: ",t2.a,t2.b) # In t2, Instance Variable 'a' is not Available, hence Static Variable a=10 will be considered and 
# Instance Variable b is readily available in t2 hence it will be displayed directly.

t1:  888 999
t2:  10 20


In [8]:
class Test:
    a=10
    def __init__(self):
        self.b = 20
        
    def m1(self):
        self.a=888
        self.b=999
        
t1=Test() # on calling this Static Variable a =10 and Instance Variable b=20 are available
t2=Test() # on calling this Static Variable a =10 and Instance Variable b=20 are available
t1.m1() # on calling this method m1, Instance Variable a=888 will created in t1 and b=20 will be replaced with 999 in t1
t2.m1() # on calling this method m1, Instance Variable a=888 will created in t2 and b=20 will be replaced with 999 in t2
print("t1: ",t1.a,t1.b) #Since both the instance variables are available in t1 i.e a=888,b=999 will be displayed 
print("t2: ",t2.a,t2.b) #Since both the instance variables are available in t2 i.e a=888,b=999 will be displayed 

t1:  888 999
t2:  888 999


In [9]:
class Test:
    a=10
    def __init__(self):
        self.b = 20
    
    @classmethod    
    def m1(cls):
        cls.a=888
        cls.b=999
        
t1=Test() # on calling this Static Variable a =10 and Instance Variable b=20 are available
t2=Test() # on calling this Static Variable a =10 and Instance Variable b=20 are available
t1.m1() # on calling m1 method, Static variable a=10 will be replaced with 888 and static variaable b=999 will be created at class level
print("t1: ",t1.a,t1.b) # Since Instance Variable 'a' is not Available in t1, hence static variable a=888 will be considered and
# Instance Variable b is readily available, hence a=888 and b=20 will be dispalyed
print("t2: ",t2.a,t2.b)  # Since Instance Variable 'a' is not Available in t2, hence static variable a=888 will be considered and
# Instance Variable b is readily available, hence a=888 and b=20 will be dispalyed
print('Test: ',Test.a,Test.b) # The Updated Static Variable a=888 and newly Created Static Variable b=999 will be displayed.  

t1:  888 20
t2:  888 20
Test:  888 999


### How to Delete Static Variables of a Class:
1) We can delete static variables from anywhere by using the following syntax <br>
> <span style='color:orange'>**del**</span> <span style='color:green'>**classname.variablename**</span>

2) But inside classmethod we can also use cls variable<br>
> <span style='color:orange'>**del**</span> <span style='color:green'>**cls.variablename**</span>

In [10]:
# Deleting Static Variable from inside the class
class Test:
    a=10
    @classmethod
    def m1(cls):
        del Test.a
print(Test.__dict__) # a will be present in the Class Dictionary, but once we call the m1 method, a will be deleted from class.

{'__module__': '__main__', 'a': 10, 'm1': <classmethod object at 0x0000018741E4AAC0>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}


In [11]:
# Deleting Static Variable from inside the class
class Test:
    a=10
    @classmethod
    def m1(cls):
        del Test.a
        
Test.m1() # on calling this m1 method, Static Variable a=10 will be deleted.        
print(Test.__dict__) # Static Variable 'a' will not be available in Class Dictionary.

{'__module__': '__main__', 'm1': <classmethod object at 0x0000018741E4A640>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}


In [12]:
# Deleting Static Variable from inside the class
class Test:
    a=10
    @classmethod
    def m1(cls):
        #del Test.a
        del cls.a # we can do like this also for deleting the static variable
        
Test.m1() # on calling this m1 method, Static Variable a=10 will be deleted.        
print(Test.__dict__) # Static Variable 'a' will not be available in Class Dictionary.

{'__module__': '__main__', 'm1': <classmethod object at 0x0000018741D79520>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}


In [13]:
# Deleting Static Variable from outside the class
class Test:
    a=10
    @classmethod
    def m1(cls):
        #del Test.a
        del cls.a # we can do like this also for deleting the static variable
        
del Test.a # directly deleting the Static Variable from outside of the Test Class        
print(Test.__dict__) # Static Variable 'a' will not be available in Class Dictionary.

{'__module__': '__main__', 'm1': <classmethod object at 0x0000018741E4A8E0>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}


In [22]:
class Test:
    a=10
    def __init__(self):
        Test.b=20
        del Test.a
    
    def m1(self):
        Test.c=30
        del Test.b
        
    @classmethod
    def m2(cls):
        cls.d=40
        del Test.c
        
    @staticmethod
    def m3():
        Test.e=50
        del Test.d
        
print(Test.__dict__) # a will be present in the class dict
print()
t=Test() #After creating object, Static Variable a=10 will be deleted and Static Variable b=20 will added automaticlly by __init__
print(Test.__dict__) # b:20 will be present in the class dict and a will be deleted
print()
t.m1() # b=20 will be deleted and c=30 will be added on calling the m1 method
print(Test.__dict__) # c:30 will be present in the class dict and b:20 will be deleted
print()
t.m2() # c=30 will be deleted and d=40 will be added on calling the class method m2
print(Test.__dict__) # d:40 will be present in the class dict and c:30 will be deleted
print()
t.m3() # d=40 will be deleted and e=50 will be added on calling the static method m3
print(Test.__dict__) # e:50 will be present in the class dict and d:40 will be deleted
print()
del Test.e
print(Test.__dict__) # e:50 also deleted and No static variable is present in the Class Dictionary. 

{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x0000018741E66AF0>, 'm1': <function Test.m1 at 0x0000018741E66A60>, 'm2': <classmethod object at 0x0000018741E4A3A0>, 'm3': <staticmethod object at 0x0000018741E4AA00>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None}

{'__module__': '__main__', '__init__': <function Test.__init__ at 0x0000018741E66AF0>, 'm1': <function Test.m1 at 0x0000018741E66A60>, 'm2': <classmethod object at 0x0000018741E4A3A0>, 'm3': <staticmethod object at 0x0000018741E4AA00>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None, 'b': 20}

{'__module__': '__main__', '__init__': <function Test.__init__ at 0x0000018741E66AF0>, 'm1': <function Test.m1 at 0x0000018741E66A60>, 'm2': <classmethod object at 0x0000018741E4A3A0>, 'm3': <staticmethod object at 0x0000018741E4AA00>, '__dict__'

**Conclusions:**<br><br>
⚽ We can delete Static Variables either by using **Class Name** or **cls** variable<br>

> **Note:** We cannot modify/delete static variables by using object reference or self. But we can access static variables by using object reference/self and class Name<br><br>

⚽ If we are trying to modify, then a new instance variable will be added to that particular object.<br>
⚽ t1.a = 70 <br>
⚽ If we are trying to delete then we will get error.

In [24]:
class Test:
    a=10
    
t1=Test()
print(t1.a) # we can access the static variable using object reference.
del t1.a # We will get attribute error, since we can't use object reference or self to delete static variable

10


AttributeError: a

In [25]:
del Test.a # this is perfectly valid as we are using Class Name 

### Instance Variable vs Static Variable

<img src = "images/instance_vs_static_variables.png" width = 700>

## 3) Local Variables: 
⚽ Sometimes to meet temporary requirements of programmer, we can declare variables inside a method directly without using self,class name or cls variable. such type of variables are called local variable or temporary variables.<br>
⚽ Local variables can be used to hold temporary results.<br> 
⚽ Local variables will be created at the time of method execution and destroyed once method completes.<br>
⚽ Local variables of a method cannot be accessed from outside of method.

In [9]:
class Student:
    
    college_name = 'VJIT' # Static Variable
    
    def __init__(self,name,rollno,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  # Instance Variable
        self.rollno = rollno # Instance Variable
        self.marks = marks # Instance Variable
        
    def info(self):
        x=10 # Local Variable
        for i in range(x):
            print(i)

In [3]:
class Test:
    
    @staticmethod
    def average(list1):
        result = sum(list1)/len(list1) # to hold sum(list1)/len(list1) formula, temperary variable must be used. It is called a local variable
        print("Average = ",result)
    
    @staticmethod
    def wish(name):
        for i in range(5): # here 'i' is the local variable since it is holding the temporary sequence values of range 
            print(i," Hello,",name)
    
list1 = [10,20,30,40,50]
Test.average(list1)
print()
Test.wish("Sairam")

Average =  30.0

0  Hello, Sairam
1  Hello, Sairam
2  Hello, Sairam
3  Hello, Sairam
4  Hello, Sairam


In [5]:
class Test:
    
    def m1(self):
        a=10
        print(a)
        
    def m2(self):
        print(a) # We can't the access the local variables of the other methods
        
t=Test()
t.m1()
t.m2() # We will get NameError, since local variables of one method can't be accessed to other methods

10


NameError: name 'a' is not defined

#### Mini Bank Application Example to Understand Instance,Static and Local variables

In [6]:
class Customer:
    '''This class describes bank operations'''
    bankname = "Kotak Bank" # Static Variable
    def __init__(self,name,balance = 0.0):
        self.name = name # Instance Variable
        self.balance = balance ## Instance Variable

    def deposit(self,amount): # Intsance Method
        self.balance = self.balance + amount
        print("After Deposit, Balance is: ",self.balance)
        print()
        
    def withdraw(self,amount): ## Intsance Method
        if amount>self.balance:
            print("Insufficient Funds...cannot perform this operation")
            print()
        else:
            self.balance = self.balance-amount
            print("After Withdraw, balance is: ",self.balance)
            print()
            
print("Welcome to ",Customer.bankname)
print()
name = input("Enter Your Name:")
c=Customer(name)
while True:
    print()
    print('d - deposit\nw - withdraw \ne - exit')
    print()
    option=input("Choose your option:")
    print()
    if option.lower()=='d':
        amount = float(input("Enter amount to deposit:"))
        c.deposit(amount)
    elif option.lower() == 'w':
        amount = float(input("Enter amount to withdraw:"))
        c.withdraw(amount)
    elif option.lower() == 'e':
        print("Thanks for Banking")
        break
    else:
        print("your option is invalid, please chose valid option")

Welcome to  Kotak Bank

Enter Your Name:sairam

d - deposit
w - withdraw 
e - exit

Choose your option:d

Enter amount to deposit:10000
After Deposit, Balance is:  10000.0


d - deposit
w - withdraw 
e - exit

Choose your option:t

your option is invalid, please chose valid option

d - deposit
w - withdraw 
e - exit

Choose your option:w

Enter amount to withdraw:20000
Insufficient Funds...cannot perform this operation


d - deposit
w - withdraw 
e - exit

Choose your option:w

Enter amount to withdraw:8000
After Withdraw, balance is:  2000.0


d - deposit
w - withdraw 
e - exit

Choose your option:e

Thanks for Banking


# Understanding Eveything in Types of Methods - Instance, Static and Class 

## Types of Methods:<br>
Inside Python class 3 types of methods are allowed<br>
> 1) Instance Methods<br>
> 2) Class Methods<br>
> 3) Static Methods<br><br>

### 1) Instance Methods: 
⚽ Inside method implementation if we are using atleast one instance variable, then such type of methods are called instance methods.<br> ⚽ Inside instance method declaration, we have to pass self variable. **def m1(self):**<br>
⚽ The first argument to the instance method is always **self**,which is reference variable to that current object.<br>
⚽ Within the class we can call instance method by using self variable and from outside of the class we can call by using object reference.

In [4]:
class Student:
    
    college_name = 'VJIT' # Static Variable
    
    def __init__(self,name,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  # Instance Variable
        self.marks = marks # Instance Variable
        
    def display(self): # This is an Instance Method, Since Instance Atleast one Instance Variable used in this method. 
        print("Hi ",self.name) # Instance Variable is used
        print("Your Marks are : ",self.marks) # Instance Variable is used
        
    def grade(self): # Instance Method
        if self.marks > 60: # Instance Variable is used
            print("You got First Class")
        elif self.marks >= 50: # Instance Variable is used
            print("You got second Class")
        elif self.marks >= 35: # Instance Variable is used
            print("You got Third Class")
        else:
            print("You are Failed")
            
n = int(input("Enter No. of Students: "))

for i in range(n):
    name = input("Enter Student Name: ")
    marks = int(input("Enter Student Marks: "))
    s = Student(name,marks)
    s.display()
    s.grade()
    print()

Enter No. of Students: 2
Enter Student Name: sairam
Enter Student Marks: 90
Creating instane variables and performing initialization...
Hi  sairam
Your Marks are :  90
You got First Class

Enter Student Name: dhana
Enter Student Marks: 80
Creating instane variables and performing initialization...
Hi  dhana
Your Marks are :  80
You got First Class



## Setter and Getter Methods: 
 
We can set and get the values of instance variables by using getter and setter methods.<br><br>

### Setter Method:
setter methods can be used to set values to the instance variables. setter methods also known as mutator methods.<br>

**Syntax:**<br>

<span style='color:orange'>**def**</span> <span style='color:blue'>**setVariable(self,variable):<br> 
&emsp;&emsp;self.variable = variable**</span><br><br>


**Example:**

In [5]:
def setName(self,name):
    self.name=name

### Getter Method: 

Getter methods can be used to get values of the instance variables. Getter methods also known as accessor methods.<br><br>
**Syntax:**<br><br>
<span style='color:orange'>**def**</span> <span style='color:blue'>**getVariable(self): <br>
&emsp;&emsp;return self.variable**</span><br><br>

**Example:**

In [6]:
def getName(self): 
    return self.name

**Example of Getter and Setter methods:**

In [7]:
class Student:
    def setName(self,name):
        self.name = name
    
    def getName(self):
        return self.name
    
    def setMarks(self,marks):
        self.marks = marks
        
    def getMarks(self):
        return self.marks
    
n = int(input("Enter no. of students:"))
students = []
for i in range(n):
    s = Student()
    name = input("Enter Student Name: ")
    marks = int(input("Enter Student Marks: "))
    s.setName(name)
    s.setMarks(marks)
    students.append(s)
    
for s in students:
    print("Hello ",s.getName())
    print("Your Marks are:",s.getMarks())
    print()

Enter no. of students:3
Enter Student Name: sairam
Enter Student Marks: 100
Enter Student Name: dhana
Enter Student Marks: 90
Enter Student Name: prasad
Enter Student Marks: 90
Hello  sairam
Your Marks are: 100

Hello  dhana
Your Marks are: 90

Hello  prasad
Your Marks are: 90



For Clear Explanation of Getter and Setter Methods, find the link https://www.python-course.eu/python3_properties.php

### 2) Class Methods:

⚽ Inside method implementation if we are using only class variables (static variables) and if we are not usingg any instance variable, then that method is no way related to a particular object and it is class level method, then such type of methods we should declare as class method.<br>
⚽ We can declare class method explicitly by using **@classmethod** decorator.<br>
⚽ The first argument of the class method is always **cls**, which is reference variable to class object at the time of declaration **eg:** def m1(cls):<br>
⚽ For every class one special object will be created by PVM to maintain class level information, which is nothing but class level object. **cls** is the reference variable pointing to that object.<br>
⚽ We can call classmethod by using classname or object reference variable.

In [13]:
class Test:
    
    @classmethod
    def m1(cls):
        print(id(cls))
        
print(id(Test))
Test.m1()

1795643957216
1795643957216


As seen above, address of the class object and address of the cls are pointing to the same object.

In [1]:
class Bird:
    
    wings = 2
    
    @classmethod # Declaring class method
    def fly(cls,name):
        print("{} flying with {} wings".format(name,cls.wings)) # only static variable of Bird Class is used with cls. No istance Variables used
        
Bird.fly('Parrot')
Bird.fly('Eagle')

Parrot flying with 2 wings
Eagle flying with 2 wings


In [3]:
# Program to track the Number of Objects created for a Class:

class Test:
    
    count = 0 # Static Variable
    def __init__(self):
        Test.count = Test.count + 1 # For every object we create, count will be incremented. We are accessing the static variable
        # count with Class Name. 
    @classmethod
    def Get_No_of_Objects(cls):
        print("The No. of objects created:",cls.count)
        
Test.Get_No_of_Objects() # will be 0 since no object is created yet.
t1=Test()
t2=Test()
Test.Get_No_of_Objects() # Will be 2 since two objects are created above.
t3=Test()
t4=Test()
t5=Test()
Test.Get_No_of_Objects() # will be 5, since 5 objects are created in total.

    

The No. of objects created: 0
The No. of objects created: 2
The No. of objects created: 5


In [25]:
class Student:
    
    college_name = 'VJIT' # Static Variable
    
    def __init__(self,name,rollno,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  # Instance Variable
        self.rollno = rollno # Instance Variable
        self.marks = marks # Instance Variable
        
    def get_student_info(self): # This is an Instance Method, Since Instance Atleast one Instance Variable used in this method. 
        print("Student Name : ",self.name)
        print("Student rollno : ",self.rollno)
    
    @classmethod
    def college(cls): # Class Method
        print("Student is From {} college".format(cls.college_name))

Student.college()

Student is From VJIT college


# Instance Method vs Class Method

<img src = 'images/instance_vs_class_methods.png' width = 700>

### 3) Static Methods: 

⚽ Inside a method Implementation, if we are not using any instance variable or Static variables, such type of methods are called **general utility methods** and these methods we have to declare as static methods.<br> 
⚽ For Static Methods, we won't provide **self** or **cls** arguments at the time of declaration.<br> 
⚽ We can declare static method explicitly by using **@staticmethod** decorator<br>
⚽ We can access static methods by using classname or object reference, But recommended to use Class Name<br>

In [28]:
class Student:
    
    college_name = 'VJIT' # Static Variable
    
    def __init__(self,name,rollno,marks):
        print("Creating instane variables and performing initialization...")
        self.name = name  # Instance Variable
        self.rollno = rollno # Instance Variable
        self.marks = marks # Instance Variable
        
    def get_student_info(self): # This is an Instance Method, Since Instance Atleast one Instance Variable used in this method. 
        print("Student Name : ",self.name)
        print("Student rollno : ",self.rollno)
    
    @classmethod
    def college(cls): # Class Method, Only static variable is used. No Instance Variables should be used inside classmethod.
        print("Student is From {} college".format(cls.college_name))
        
    @staticmethod
    def getsum(a,b): # Static Method. No Instance or Static Variables should used in Static Method. Only Local Variables used. 
        sum = a+b
        print(sum)

Student.getsum(1,2)

3


In [6]:
# Example for Static Method

class RKmath:
    
    @staticmethod
    def add(x,y): # This Method is nowhere related to Instance or Static Variables. Hence, Declaring as Staticmethod for general utility
        print("The SUM: ",x+y)
        
    @staticmethod
    def product(x,y):
        print("The Product: ",x*y)
    
    @staticmethod
    def average(x,y):
        print("The Average: ",(x+y)/2)
        
RKmath.add(10,20) # Directly calling the staticmethods with Class Name "RKmath"
RKmath.product(10,20)
RKmath.average(10,20)

The SUM:  30
The Product:  200
The Average:  15.0


## Instance Methods vs Class Method vs Static Methods 

 - If we are using only Instance Variables ==> **Instance Method**<br>
 - If we are using only Static Variables ==> **Class Method**<br>
 - If we are using Instance Variables and Static Variables ==> **Instance Method**<br>
 - If we are using Instance Variables and Local Variables ==> **Instance Method**<br>
 - If we are using Static Variables and Local Variable ==> **Class Method**<br>
 - If we are using only Local Variables ==> **Static Method**<br>

**What happens if we are not using any decorator ?**

1) For **Class Methods** : The Decorator **@classmethod** is **Mandatory** ==> if we dont give decorator, its not treated as class method.<br>
2) For **Static Methods** : The Decorator **@staticmethod** is **Optional**<br>
3) For **Instance Methods** : The Decorator is Not Required.<br><br>

If a Method is Not given a decorator, it can be a **Instance Method** or a **Static Method**.<br>
We can decide a method, Instance or Static Method as follows:<br>
> class Test:<br>&ensp;&ensp;&ensp; def m1(x):<br>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;pass<br>t1 = Test()<br>**t1.m1()** # calling with method m1 with object reference<br>**Test.m1()** # calling the method m1 with class name<br> 

> If we are calling the above method by using Object Reference i.e **t1.m1()** ==> Then the method m1 acts as **Instance Method**<br>
> if we are calling the above method by using Class Name i.e **Test.m1()** ==> Then the method m1 acts as **Static Method** 


In [7]:
class Test:
    
    def m1():
        print("Some Method")
        
t1=Test()
t1.m1() 

TypeError: m1() takes 0 positional arguments but 1 was given

Because m1 doesn't have any arguments. PVM consider it as Instance method and provides **self** to m1,since there are no arguments in m1. This will raise an error.

In [8]:
class Test:
    
    def m1(x): # Now giving one argument x in m1 method.
        print("Some Method")
        
t1=Test()
t1.m1() #This will work fine, PVM will pass self to x 

Some Method


In [9]:
class Test:
    
    def m1(x): # Now giving one argument x in m1 method.
        print("Some Method")
        
t1=Test()
t1.m1(10) # This will become invalid and raise error, we gave only one argument in m1 by default will be considered for self by PVM.
# and we are also passing a value to m1, which is already occupied for self hence error will raise.

TypeError: m1() takes 1 positional argument but 2 were given

In [10]:
# calling m1 with Class Name

class Test:
    
    def m1():
        print("Some Method")
        
Test.m1() # This acts as Static Method since we are calling m1 without decorator with Class Name

Some Method


In [11]:
class Test:
    
    def m1(x):
        print("Some Method")
        
Test.m1() # This a Static Method, We have to pass a value compulsary to m1, if not error will be raised.

TypeError: m1() missing 1 required positional argument: 'x'

# Accessing Members of one class inside another class

We can access members of one class inside another class.<br><br>
Lets understand with one simple example.

In [12]:
class Employee: # Class 1
    
    def __init__(self,eno,ename,esal):
        self.eno = eno
        self.ename = ename
        self.esal = esal
        
    def display(self):
        print("Employee Number:",self.eno)
        print("Employee Name:",self.ename)
        print("Employee Salary:",self.esal)
        
class Manager: # Class 2
    
    def UpdateEmpSal(emp):
        emp.esal = emp.esal + 1000 # This will access the self.esal from Employee Class
        emp.display() ## This will access the display method from Employee Class
        
emp = Employee(101,'Sairam',45000)
Manager.UpdateEmpSal(emp)

Employee Number: 101
Employee Name: Sairam
Employee Salary: 46000


# Inner Classes

Sometimes we can declare a class inside another class, such type of classes are called inner classes.<br><br>

**When We should go for Inner Classes:**<br><br>
<span style='color:green'>***Without existing one type of object, if there is no chance of existing another type of object***</span>, then we should go for inner classes.

For Example:<br><br>
**Without existing university object, there is no chance of existing department object.**

A university consists of Several Departments like EEE,ECE,CSE,IT,MECH,MBA etc. All the Departments will exist if and only if the university exists.<br> If the University is Removed, All the Departments will not exist.<br><br>
class University: **# Outer Class Object**<br> 
&emsp;&emsp;..............<br>
&emsp;&emsp;..............<br>
&emsp;&emsp;..............<br>
&emsp;&emsp;&emsp;class Department:           **# Inner Class Object**<br> 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;pass<br><br>
Without existing outer class object, there is no chance of inner class object existence.<br><br>
**Some More Examples:**<br>

<img src="images/inner_class_ex.png" width=600>

**Advantages of Inner Classes:**<br>
1) It improves modularity of the application i.e we can define the the Inner class(department) wherever it is required inside an outerclass.<br>
2) It improves security of the application i.e. We can't access Inner class(department) information without Accessing the Outer Class (university).


**Demo Program to understand Inner Classes:**

In [2]:
class Outer:
    
    def __init__(self):
        print("Outer Class object creation")
        
    class Inner:
        
        def __init__(self):
            print("Inner Class object creation")
            
        def m1(self):
            print("Inner Class Method")
            
o = Outer() # Acessing Outer Class
i = Inner() # We directly can't access Inner Class without accesiing Outer Class. This will raise an error.
i.m1

Outer Class object creation


NameError: name 'Inner' is not defined

In [3]:
o = Outer() # Acessing Outer Class
i = o.Inner() # We should access Inner Class from the Outer Class like this syntax using . notation
i.m1() # Accessing the method from the inner class.

Outer Class object creation
Inner Class object creation
Inner Class Method


In [5]:
i=Outer().Inner() # This is also valid.
i.m1()

Outer Class object creation
Inner Class object creation
Inner Class Method


In [6]:
Outer().Inner().m1() # This Single Line code is also valid

Outer Class object creation
Inner Class object creation
Inner Class Method


**Nesting of Inner Classes Demo Program:**

In [12]:
class Outer:
    def __init__(self):
        print("Outer Class Object Creation")
        
    class Inner:
        def __init__(self):
            print("Inner Class Object Creation")
            
        class InnerInner:
            def __init__(self):
                print("InnerInner Class Object Creation")
                    
            def m1(self):
                print("Nested Inner Class Method")
                    
# To call the m1 method
print("********* With Sytax 1 **********")
o=Outer()
i=o.Inner()
ii=i.InnerInner()
ii.m1()
print()
print("********* With Sytax 2 **********")
Outer().Inner().InnerInner().m1()

********* With Sytax 1 **********
Outer Class Object Creation
Inner Class Object Creation
InnerInner Class Object Creation
Nested Inner Class Method

********* With Sytax 2 **********
Outer Class Object Creation
Inner Class Object Creation
InnerInner Class Object Creation
Nested Inner Class Method


In [16]:
class Outer:
    def __init__(self):
        print("Outer Class Object Creation")
        
    class Inner:
        def __init__(self):
            print("Inner Class Object Creation")
            
        class InnerInner:
            def __init__(self):
                print("InnerInner Class Object Creation")
                    
            @staticmethod
            def m1():
                print("Nested Inner Class Static Method")
                    

print("********* Accessing Static Method **********")
Outer().Inner().InnerInner.m1()
# We don't need to create InnerInner Object for accessing the static method, we can access it directly from Inner class with above syntax.

********* Accessing Static Method **********
Outer Class Object Creation
Inner Class Object Creation
Nested Inner Class Static Method


In [17]:
# Example 2

class Human:
    class Head:
        def talk(self):
            print('talking....')
            
        class Brain:
            def think(self):
                print("Thinking....")
                
human = Human()
head = human.Head()
head.talk()
brain = head.Brain()
brain.think()

talking....
Thinking....


Till now we have been creating the objects individually, But we want to automate the creation of objects. like If we create Human object automatically the Head and Brain Objects should also be created.<br><br> We can automate it like below example:

In [25]:
# Example 3
class Human:
    
    def __init__(self,name):
        self.name = name
        self.head = self.Head() # directly calling the Head class from constructor upon creating a human object
        
    def info(self):
        print("Hello, My Name is ",self.name)
        print("I am always busy with")
        self.head.talk() # Since Head class is already called an information is available, this will be displayed
        self.head.brain.think() # On calling the Head class, Constructor will automatically call the Brain class and the brain info will be accessed.
        
    class Head: # Head Class will respond to the self.Head() from the constructor of Human Class
        
        def __init__(self):
            self.brain = self.Brain() # Calling the Brain Class from Head class Constructor upon a call from Human class Constructor.
            
        def talk(self):
            print("Talking...") # This will be printed for self.head.talk()
            
        class Brain: # Brain class will respond to self.Brain() from the constructor of Head Class which is called with self.Head() from the constructor of Human Class
            def think(self):
                print("Thinking...")
              
human = Human("Sairam")
human.info()          

Hello, My Name is  Sairam
I am always busy with
Talking...
Thinking...


In [29]:
# Example 3
# Without a person existance, date of birth can't be defined. Lets do it with code

class Person:
    
    def __init__(self,name,dd,mm,yyyy): # on calling the person class, all the parameters given will be passed to respective instance variables and arguments.
        print("Person Object Creation....")
        self.name = name # 
        self.dob = self.DOB(dd,mm,yyyy) #dd,mm,yyyy will be passed to the DOB Class for Creating the Instance Variables in DOB Class
        
    def info(self): 
        print("Name = ",self.name)
        self.dob.display() # Since DOB Class is already called and information is available, display from DOB will be called and executed.
    
    
    class DOB: # DOB Class will respond to the self.DOB(dd,mm,yyyy) from the constructor of Person Class
        
        def __init__(self,dd,mm,yyyy): # all the parameters received from the self.DOB(dd,mm,yyyy) will be used for Instance Variables Creation
            print("DOB Object Creation")
            self.dd = dd # This will create Instance variable date 'dd'.
            self.mm = mm # This will create Instance variable month 'mm'.
            self.yyyy = yyyy # This will create Instance variable year 'yyyy'.
            
        def display(self): # upon calling this function this will be executed.
            print("DOB = {}/{}/{}".format(self.dd,self.mm,self.yyyy)) # This will be printed for self.dob.display()

p = Person("SAIRAM KANDUKURI",19,6,1996)
p.info()

Person Object Creation....
DOB Object Creation
Name =  SAIRAM KANDUKURI
DOB = 19/6/1996


This is all about Inner Classes, Hope You got the clear clarity with the above examples.<br><br>
# Nested Methods

When we require, method specific repeated functionality, then we should go for Nested Methods

In [41]:
class Test:
    def m1(self):
        a=10
        b=20
        print("The SUM",a+b)
        print("The Product",a*b)
        print("The Difference",a-b)
        print("The Average",(a+b)/2)
        print()
        # again for other values of a and b we need same functionality above.
        a=100
        b=200
        print("The SUM",a+b)
        print("The Product",a*b)
        print("The Difference",a-b)
        print("The Average",(a+b)/2)
        print()
        # again for other values of a and b we need same functionality above.
        a=1000
        b=2000
        print("The SUM",a+b)
        print("The Product",a*b)
        print("The Difference",a-b)
        print("The Average",(a+b)/2)
        
t=Test()
t.m1()

The SUM 30
The Product 200
The Difference -10
The Average 15.0

The SUM 300
The Product 20000
The Difference -100
The Average 150.0

The SUM 3000
The Product 2000000
The Difference -1000
The Average 1500.0


The above program is lenghty and memory consuming and there is no modularity. We can do the above program as below using nested methods

In [39]:
class Test:
    
    def m1(self):
        
        def calc(a,b):
            print("The SUM",a+b)
            print("The Product",a*b)
            print("The Difference",a-b)
            print("The Average",(a+b)/2)
            print()
            
        calc(10,20)
        calc(100,200)
        calc(1000,2000)
        
t=Test()
t.m1()

The SUM 30
The Product 200
The Difference -10
The Average 15.0

The SUM 300
The Product 20000
The Difference -100
The Average 150.0

The SUM 3000
The Product 2000000
The Difference -1000
The Average 1500.0



# Garbage Collections

⚽ In old languages like C++, programmer is responsible for both creation and destruction of objects.Usually programmer taking very much care while creating object, but neglecting destruction of useless objects. Because of his neglectance, total memory can be filled with useless objects which creates memory problems and total application will be down with Out of memory error <br><br>
⚽ But in Python, We have some assistant which is always running in the background to destroy useless objects.Because this assistant the chance of failing Python program with memory problems is very less. This assistant is nothing but Garbage Collector.<br><br>
⚽ Hence the main objective of Garbage Collector is to destroy useless objects.<br><br>
⚽ If an object does not have any reference variable then that object eligible for Garbage Collection. i.e if the reference count is zero, then only object is eligible for garbage collector.<br>

**How to enable and disable Garbage Collector in our Program:**<br>
By default Gargbage collector is enabled, but we can disable based on our requirement. In this context we can use the following functions of gc module.<br><br>
1) **gc.isenabled()** ==> Returns True if GC enabled <br>
2) **gc.disable()** ==> To disable GC explicitly <br>
3) **gc.enable()** ==> To enable GC explicitly<br>

In [2]:
import gc # we need to import the gc module for performing garbage collector functions
print(gc.isenabled()) # By default, GC is Always Enabled. So this will return TRUE

True


In [4]:
gc.disable() # We can disable Garbage Collector (GC) if we don't want.
print(gc.isenabled())

False


In [5]:
gc.enable() # We can again Enable the Garbage Collector like this.
print(gc.isenabled())

True


# Destructors

⚽ Destructor is a special method and the name should be **\_\_del\_\_** <br>
⚽ Just before destroying an object Garbage Collector always calls destructor to perform clean up activities (Resource deallocation activities like close database connection, close network connection etc).<br> 
⚽ Once destructor execution completed then Garbage Collector automatically destroys that object.<br><br>
**Note:** The job of destructor is not to destroy object and it is just to perform clean up activities.<br>

In [11]:
# Example

import time

import time

class Test:
    
    def __init__(self):
        print("Object Initialization Activities")
    
    def __del__(self):
        print("Fulfiling Last wish and performing cleanup activities...")
        
t = Test() # Here only Object Initialization is happening, since t is pointing to Test object. So, Destructor will not exceute since there are no eligible objects for destruction
# t = None
time.sleep(10)
print("End of Application")
        
t = Test() # Here only Object Initialization is happening, since t is pointing to Test object. So, Destructor will not exceute since there are no eligible objects for destruction
# t = None
time.sleep(10)
print("End of Application")

Object Initialization Activities
End of Application


**In above example, only Object Initialization is happening, since t is pointing only to Test object. So, Destructor will not exceute since there are no eligible objects for Garabge Collection**

In [13]:
t = Test()
t = None # Now t is poinitng to None, Instead of Test() object. Nothing is pointing to Test. Hence, Test Object is eliglbe for Grabage Collection. So __del__ will be executed.
time.sleep(10)
print("End of Application")

Object Initialization Activities
Fulfiling Last wish and performing cleanup activities...
End of Application


Now t is poinitng to None, Instead of Test() object. Nothing is pointing to Test. Hence, Test Object is eliglbe for Grabage Collection. So **\_\_del\_\_** will be executed.

**Note:** <br>
1) If the object doesn't contain any reference variable then only it is eligible for garbage collection. i.e. if the reference count is zero then only object eligible for Garbage Collection.<br><br>
2) Once Control reaches end of program, all objects which are created as the part of that program are by default eligible for Garbage Collection.

In [5]:
# Example for 2) Point
import time

class Test:
    
    def __init__(self):
        print("Constructor Execution")
    
    def __del__(self):
        print("Destructor Execution")
        
m1=Test()
m2=m1
m3=m1
# all m1,m2,m3 are pointing to Test object
del m1 # this will not delete Test object, since m2 and m3 are still pointing to Test Object
time.sleep(5)
print("object not destroyed after deleting t1")
del m2 # this will not delete Test object, since m3 is still pointing to Test Object
time.sleep(5)
print("Object not destroyed even after deleting t2")
print("Deleting Last Reference")
del m3 #After deleting last reference m3 of Test Object. Now Test Object is eligble for Garbage Colection.
print("End of application")

Constructor Execution
object not destroyed after deleting t1
Object not destroyed even after deleting t2
Deleting Last Reference
Destructor Execution
End of application


In [6]:
# Example 3

import time

class Test:
    
    def __init__(self):
        print("Constructor Execution")
    
    def __del__(self):
        print("Destructor Execution")
        
l = [Test(), Test(), Test()]
print("Making List object eligible for GC")
del l # on deleting the list, List and all objects inside list for Garbage Collection
time.sleep(5)
print("End of Application")

Constructor Execution
Constructor Execution
Constructor Execution
Making List object eligible for GC
Destructor Execution
Destructor Execution
Destructor Execution
End of Application


# The 3 Important Interview Questions

Q1. What is the difference between **del t1** and **t1=None** ?

In [8]:
# If we don't want both object and reference variable then go for del.
class Test:
    def __init__(self):
        print("Constructor")
        
    def __del__(self):
        print("Destructor")
        
t=Test()
del t # reference variable t be deleted, and Test object is eligible for GC
print("End of Application")

Constructor
Destructor
End of Application


In [9]:
print(t) # can't use t anymore since it is destroyed.

NameError: name 't' is not defined

In [10]:
# if you don't want object, but need reference variable. Better to use this reassignment approach
class Test:
    def __init__(self):
        print("Constructor")
        
    def __del__(self):
        print("Destructor")
        
t=Test()
t=None # By using this, Test is no longer reference to t, t assigned to None now.
# Hence, Test() is eligble for GC.
print("end of application")

Constructor
Destructor
end of application


In [11]:
print(t) # t is avialble

None


Q2. How to find number of references of an object ?

we have to import **sys** module. it contains **getrefcount()** function for this purpose. <br>
**sys.getrefcount(objectreference)** is the syntax

In [12]:
import sys

class Test:
    pass
t1=Test()
print(sys.getrefcount(t1)) # one is Self and other is t1 pointing to Test object

2


In [13]:
import sys

class Test:
    pass
t1=Test()
t2=t1
t3=t2
t4=t3
print(sys.getrefcount(t1))

5


In [14]:
del t3,t4 # deleting two references, now we should get 3
print(sys.getrefcount(t1))

3


**Note:** For every object, Python internally maintains one default reference variable self.

Q3. What id the difference between Constructor and Destructor?<br>
<img src="images/constructor_vs_destructor.png" width = 700>

# ========================== PART - 2 ==========================

## Using Members of One Class inside Another Class: 
We can use members of one class inside another class by using the following ways<br>
1) **By Composition (Has-A Relationship)**<br>
2) **By Inheritance (IS-A Relationship)**

### 1) By Composition (Has-A Relationship):<br>
 - By using Class Name or by creating object we can access members of one class inside another class is nothing but composition (Has-A Relationship).<br>
 - The main advantage of Has-A Relationship is Code Reusability i.e. **write once, use anywhere**<br>
 
 <img src="images/HAS-A.png" width = 700><br>This Type of Relations between the objects is called **Composition** or **HAS-A Relationship**<br>
 <img src="images/HAS-A2.png">

In [17]:
# Example 1

class Engine:
    
    def __init__(self):
        self.power = '125KW'
    
    def m1(self):
        print("Engine Specific Functionality")
        
class Car:
    
    def __init__(self):
        self.engine = Engine() # Class Car is accessing the Engine object and its Functionalities
        
    def CarEngine(self):
        print("Car required Engine Functionality")
        self.engine.m1() # Engine Specific Functionality is used in Car Class
        print(self.engine.power)
        
c = Car()
c.CarEngine()

Car required Engine Functionality
Engine Specific Functionality
125KW


In [20]:
# Example 2
# Employee HAS-A Car

class Car:
    def __init__(self,name,model,color):
        self.name = name
        self.model = model
        self.color = color
        
    def getInfo(self):
        print("Car Name : {}, Model : {}, Color : {}".format(self.name,self.model,self.color))
        
class Employee:
    def __init__(self,ename,eno,car):
        self.ename = ename
        self.eno = eno
        self.car = car
    
    def EmpInfo(self):
        print("Employee Name : ",self.ename)
        print("Employee Number : ",self.eno)
        print("Employee Car Info:")
        self.car.getInfo()
        
car = Car("Audi",'2.5V','Grey')
emp = Employee("Sairam",101,car)
emp.EmpInfo()

Employee Name :  Sairam
Employee Number :  101
Employee Car Info:
Car Name : Audi, Model : 2.5V, Color : Grey


In the above program Employee class Has-A Car reference and hence Employee class can access all members of Car class.

**Exmaple 3**<br>
I want to develop RK News Channel Functionality where i want to present sports news, Movie news etc.<br><br>
1) i have SportsNews Class which consists of Sports Information.<br>
2) i have MovieNews Class which consists of Movies Information.<br>
3) i have PoliticsNews Class which consists of Politics Information.<br>
<br>RKNews should be created and all the information of Above 3 News should be accessible. 

In [24]:
class SportsNews:
    def SportsInfo(self):
        print("Sports Information 1.........")
        print("Sports Information 2.........")
        print("Sports Information 3.........")
        print("Sports Information 4.........")
        print()
        
class MovieNews:
    def MoviesInfo(self):
        print("Movies Information 1.........")
        print("Movies Information 2.........")
        print("Movies Information 3.........")
        print("Movies Information 4.........")
        print()

class PoliticsNews:
    def PoliticsInfo(self):
        print("Politics Information 1.........")
        print("Politics Information 2.........")
        print("Politics Information 3.........")
        print("Politics Information 4.........")
        print()


class RKNews:
    def __init__(self):
        self.sports = SportsNews()
        self.movies = MovieNews()
        self.politics = PoliticsNews()
        
    def GetTotalNews(self):
        print("Welcome to RK News:")
        print()
        self.sports.SportsInfo()
        self.movies.MoviesInfo()
        self.politics.PoliticsInfo()
        
rknews = RKNews()
rknews.GetTotalNews()

Welcome to RK News:

Sports Information 1.........
Sports Information 2.........
Sports Information 3.........
Sports Information 4.........

Movies Information 1.........
Movies Information 2.........
Movies Information 3.........
Movies Information 4.........

Politics Information 1.........
Politics Information 2.........
Politics Information 3.........
Politics Information 4.........



In [26]:
# Method 2
class SportsNews:
    def SportsInfo(self):
        print("Sports Information 1.........")
        print("Sports Information 2.........")
        print("Sports Information 3.........")
        print("Sports Information 4.........")
        print()
        
class MovieNews:
    def MoviesInfo(self):
        print("Movies Information 1.........")
        print("Movies Information 2.........")
        print("Movies Information 3.........")
        print("Movies Information 4.........")
        print()

class PoliticsNews:
    def PoliticsInfo(self):
        print("Politics Information 1.........")
        print("Politics Information 2.........")
        print("Politics Information 3.........")
        print("Politics Information 4.........")
        print()
        
class RKNews:
    def __init__(self,SportsNews,MovieNews,PoliticsNews):
        self.sports = SportsNews
        self.movies = MovieNews
        self.politics = PoliticsNews
        
    def GetTotalNews(self):
        print("Welcome to RK News:")
        print()
        self.sports.SportsInfo()
        self.movies.MoviesInfo()
        self.politics.PoliticsInfo()
    
Sports = SportsNews()
Movie = MovieNews()
Politics = PoliticsNews()

rknews = RKNews(Sports,Movie,Politics)
rknews.GetTotalNews()

Welcome to RK News:

Sports Information 1.........
Sports Information 2.........
Sports Information 3.........
Sports Information 4.........

Movies Information 1.........
Movies Information 2.........
Movies Information 3.........
Movies Information 4.........

Politics Information 1.........
Politics Information 2.........
Politics Information 3.........
Politics Information 4.........



### 2) By Inheritance (IS-A Relationship)
1) Parent to Child Relationship<br>
2) Parent class members i.e. what ever variables, methods and constructors available in the parent class by default available to the child classes and hence child class can use parent class functionality without rewriting (**Code Resusability**).<br> 
3) Child class can define new members also. Hence child class can extend parent class functionality (**Code Extendability**).<br>
<br>Hence the main advantage of inheritance is<br><br>
> 1) **Code Reusability :** We can use the code of the parent class in the child class.<br>
> 2) **Code Extendability :** we can extend existing functionality with some more extra functionality.<br><br>

**Syntax:** <span style='color:green'>**class**</span> <span style='color:blue'>**childclass**</span>**(parentclass)**<br>
<br>Example:<br><br>
**class P:** ===> Parent Class<br>
&emsp;&emsp;10 Methods<br>
**class C(P):** ===> Child Class<br>
&emsp;&emsp;5 Methods<br><br>

In the above example Parent class contains 10 methods and these methods automatically available to the child class and we are not required to rewrite those methods(Code Reusability)<br>Hence child class contains 15 methods.

In [2]:
# Example 1

class P:
    def m1(self):
        print("Parent Class Method")
        
class C(P): # Child class with parent class methods and fucntionalites. Now C has two methods
    def m2(self):
        print("Child Class Method")
        
c=C()
c.m1()
c.m2()

Parent Class Method
Child Class Method


In [4]:
# Example 2

class P:
    a=10
    def __init__(self):
        print("Parent Constructor")
        self.b = 20
        
    def m1(self):
        print("Parnet Instance Method")
        
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
# Parent Class Inheriting to child class
class C(P): # This child is lazy to have its own methods init, it only parents functionalities
    pass

c = C()
print(c.a) # 10
print(c.b) # 20
c.m1()
c.m2()
c.m3()

Parent Constructor
10
20
Parnet Instance Method
Parent Class Method
Parent Static Method


If we observe in the above example, even if the child doesn't have anything on its own. All the information we are getting from child class. It is because we are inheriting parent class to the child class.

In [9]:
# Example 3
# Developing Employee and Person Classes with inheritence
# Person consists of Name,age,person can eat and drink.
# Employee is a person with work. All the person information can be used by employee.

class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
        
    def eatndrink(self):
        print("Eat Biryani and Drink Beer")
        
class Employee(Person):
    def __init__(self,name,age,eno,esal):
        self.name = name
        self.age = age
        self.eno = eno
        self.esal = esal
    
    def work(self):
        print("Coding Python Program")
        
    def empInfo(self):
        print("Employee Name:",self.name)
        print("Employee Age:",self.age)
        print("Employee Number:",self.eno)
        print("Employee Salary:",self.esal)
        
e = Employee("Sairam",24,263,25000)
e.eatndrink()
e.work()
e.empInfo()

Eat Biryani and Drink Beer
Coding Python Program
Employee Name: Sairam
Employee Age: 24
Employee Number: 263
Employee Salary: 25000


In th above program, we have wrote self.name and self.age tough they are available in the parent class. We can remove them and access from parent class by using **super()** function. This function will be discussed later.<br><br>
From child class if we want to use parent class members, we need to call them using super() function. After calling parent class is repsonsible for creating Instance Variables name and Age of an employee.<br><br>
Lets write the above code with super()

In [10]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
        
    def eatndrink(self):
        print("Eat Biryani and Drink Beer")
        
class Employee(Person):
    def __init__(self,name,age,eno,esal):
        super().__init__(name,age) # This will call the constructor from parent class and will initialize the Instance Variables 
        self.eno = eno
        self.esal = esal
    
    def work(self): # extended method along with parent class
        print("Coding Python Program")
        
    def empInfo(self):
        print("Employee Name:",self.name)
        print("Employee Age:",self.age)
        print("Employee Number:",self.eno)
        print("Employee Salary:",self.esal)
        
e = Employee("Sairam",24,263,25000)
e.eatndrink()
e.work()
e.empInfo()

Eat Biryani and Drink Beer
Coding Python Program
Employee Name: Sairam
Employee Age: 24
Employee Number: 263
Employee Salary: 25000


# Inheritence Importance

We can avoid time consumption and also long lenghty codes with the help of inheritance.<br>We can do it by writing the most commonly used methods in the Parent class and we have to define specific methods in the child classes.<br><br>
We can access the common methods of parent class inside the child class simply with inheritance concept. 

# IS-A vs HAS-A Relationships

 - If we want to extend existing functionality with some more extra functionality then we should go for **IS-A Relationship** or **Inheritance** Concept.  <br>
 - If we dont want to extend and just we have to use existing functionality then we should go for **HAS-A Relationship** or **Composition**<br>
 - Eg: Employee class extends Person class Functionality But Employee class just uses Car functionality but not extending<br>
<img src="images/IS-A_vs_HAS-A.png" width = 600><br>
Employee **IS-A** Person<br>
Employee **HAS-A** Car

In [3]:
class Car: # This is a Compisiton Relation ship, No extendability is expecting for this in employee class. whatever there is used
    def __init__(self,name,model,color):
        self.name = name
        self.model = model
        self.color = color
        
    def getInfo(self):
        print("Car Name : {}\nModel : {}\nColor : {}".format(self.name,self.model,self.color))
        
class Person: # This is a Inheritance Relationship, Person is a Parent Class.
    def __init__(self,name,age):
        self.name = name
        self.age = age
        
    def eatndrink(self):
        print("Eat Biryani and Drink Beer")
        
class Employee(Person): # This Employee class is inherited with Person Class, We are extending code in this class along with functionalities captured from Parent Class
    def __init__(self,name,age,eno,esal,car):
        super().__init__(name,age) # This will call the constructor from parent class and will initialize the Instance Variables 
        self.eno = eno
        self.esal = esal
        self.car = car
    
    def work(self): # extended method along with parent class
        print("Coding Python Program")
        
    def empInfo(self):
        print("Employee Name:",self.name)
        print("Employee Age:",self.age)
        print("Employee Number:",self.eno)
        print("Employee Salary:",self.esal)
        print("Employee Car Information...")
        self.car.getInfo() # Employee using car class functionality, since it has reference to car object.
        
car = Car('Innova','2.5V','Grey')
e=Employee('Sairam',24,263,25000,car)
e.eatndrink() # Employee using person class Functionality
e.work() 
e.empInfo()

Eat Biryani and Drink Beer
Coding Python Program
Employee Name: Sairam
Employee Age: 24
Employee Number: 263
Employee Salary: 25000
Employee Car Information...
Car Name : Innova
Model : 2.5V
Color : Grey


# Composition vs Aggregation

**Composition:** Without existing container object if there is no chance of existing contained object then the container and contained objects are strongly associated and that strong association is nothing but Composition.<br><br>
**Eg:** University contains several Departments and without existing university object there is no chance of existing Department object. Hence University and Department objects are strongly associated and this strong association is nothing but Composition.<br>
<img src="images/composition.png" width = 600>

In [4]:
class University:
    def __init__(self):
        self.department = self.Department()
        
    class Department:
        pass

u = University() # if the university class doesn't exist, Department class will not exist. There is a strong association between two classes.

**Aggregation:** Without existing container object if there is a chance of existing contained object then the container and contained objects are weakly associated and that weak association is nothing but Aggregation.<br><br>
**Eg:** Department contains several Professors. Without existing Department still there may be a chance of existing Professor. Because professor might be shifted to other department. Hence Department and Professor Objects are weakly associated, which is nothing but Aggregation.<br>
<img src="images/aggregation.png" width=600>

In [5]:
class Professor:
    pass

class Department:
    def __init__(self,professor):
        self.professor = professor
        
professor = Professor() 
# same professor working for cs department and eee departmet. if cs dept is closed, he will still work for eee dept.
# There is weak association between objects. Hence this is called Aggregation.
csdept = Department(professor)
eeedept = Department(professor)

**Note:** In Composition, container object holds directly the contained objects, whereas in Aggregation container object just holds the references of contained objects.

In [7]:
class Student: 
    collegeName='VJIT'
    def __init__(self,name):
        self.name=name

print(Student.collegeName)
s=Student('Sairam')
print(s.name)

VJIT
Sairam


In the above example without existing Student object there is no chance of existing his name. Hence Student Object and his name are strongly associated which is nothing but Composition.<br><br>
But without existing Student object there may be a chance of existing collegeName. Hence Student object and collegeName are weakly associated which is nothing but Aggregation.<br><br>
**Conclusion:** The relation between object and its instance variables is always Composition where as the relation between object and static variables is Aggregation.

**Note:** Whenever we are creating child class object then child class constructor will be executed. If the child class does not contain constructor then parent class constructor will be executed, but parent object won't be created.

In [9]:
class P:
    def __init__(self):
        print(id(self))
class C(P):
    pass
c=C()
print(id(c))

1847836178032
1847836178032


# Types of Inheritance:

 - **Single Inheritance**<br>
 - **Multi Level Inheritance**<br>
 - **Hierarchical Inheritance**<br>
 - **Multiple Inheritance**<br>
 - **Hybrid Inheritance**<br>
 - **Cyclic Inheritance**<br>

### 1) Single Inheritance:
The concept of inheriting the properties from One Parent class to One Child class is known as single inheritance.<br>
<img src="images/single_inheritance.png" width=250><br>
P is Parent Class<br>
C is Child Class<br>
Single Parent and Single Child represents Single Inheritance.

In [10]:
class P: # Single Parent
    def m1(self):
        print("Parent Method")

class C(P): # Single child
    def m2(self):
        print("Child Method")
        
c = C()
c.m1()
c.m2()

Parent Method
Child Method


### 2) Multi Level Inheritance:
The concept of inheriting the properties from multiple classes to single class with the concept of one after another is known as multilevel inheritance.<br>
**Multiple Levels of Inheritance** ===> Multilevel Inheritance
<img src="images/multi_level_inheritance.png" width=300><br>
**P - Parent Class**<br>
**C - Child Class**<br>
**CC - Sub Child**

In [11]:
class P:
    def m1(self):
        print("Parent Method")
        
class C(P): # all the methods and functionalities from parent class P are available.
    def m2(self):
        print("Child Method")
        
class CC(C): # all the Parent Class (P) and Child Class (C) are available to sub child class (CC).
    def m3(self):
        print("Sub Child Method")
        
c=CC() # All the methods and functionalities from P and C are available to CC. 
c.m1() # hence we can access all the methods from sub child itself.
c.m2()
c.m3()

Parent Method
Child Method
Sub Child Method


### 3) Hierarchical Inheritance:

The concept of inheriting properties from one class into multiple classes which are present at same level is known as Hierarchical Inheritance.<br><br>
<span style="color:violet">**One Parent but Multiple child classes and all child classes are at same level**</span>
<img src="images/Hierachical_Inheritance.png" width=300>
**P - Parent Class**<br>
**C1 - First Child Class**<br>
**C2 - Second Child Class**<br>

In [13]:
class P:
    def m1(self):
        print("Parent Method")
        
class C1(P): # m1 from P Class and m2 from this C1 class itslef is available.
    def m2(self):
        print("First child Class Method")
        
class C2(P): # m1 from P Class and m3 from this C2 class itslef is available.
    def m3(self):
        print("Second child Class Method")
        
c1=C1()
c1.m1() # This is available from P in C1
c1.m2() # This is available from P in C2
c1.m3() # This is Not available in C3, since there is no relation between C1 and C2. Only relation b/w P and C1 is present.
# c1.m3() will raise an error

Parent Method
First child Class Method


AttributeError: 'C1' object has no attribute 'm3'

In [14]:
c1=C1()
c1.m1()
c1.m2()
c2=C2()
c2.m1()
c2.m3()

Parent Method
First child Class Method
Parent Method
Second child Class Method


### 4) Multiple Inheritance:
The concept of inheriting the properties from multiple classes into a single class at a time, is known as multiple inheritance.<br><br>
<span style="color:violet">**Multiple Parents but Single Child**</span><br><br>
**Syntax:** **class** <span style="color:green">**ClassName**</span>(<span style="color:blue">**ParentClass_1,ParentClass_2**</span>) 
<img src="images/Multiple_Inheritance.png" width=300>
**P1 - First Parent Class**<br>
**P2 - Second Parent Class**<br>
**C - Child Class**

In [15]:
class P1:
    def m1(self):
        print("First Parent Method")
        
class P2:
    def m2(self):
        print("Second Parent Method")
        
class C(P1,P2): # All the methods from P1 and P2 are available to Child Class C.
    def m3(self):
        print("Child Method")
        
c=C()
c.m1()
c.m2()
c.m3()

First Parent Method
Second Parent Method
Child Method


If the same method is inherited from both parent classes, then Python will always consider the order of Parent classes in the declaration of the child class.<br><br>
**class C(P1, P2):** ==> P1 method will be considered<br>
**class C(P2, P1):** ==> P2 method will be considered

In [17]:
class P1:
    def m1(self):
        print("First Parent Method")
        
class P2:
    def m1(self):
        print("Second Parent Method")
        
class C1(P1,P2): # m1 method from P1 will be considered.
    def m2(self):
        print("Child Method")
        
class C2(P2,P1): # m1 method from P2 will be considered.
    def m2(self):
        print("Child Method")
        
c1=C1()
c1.m1()
c1.m2()
c2=C2()
c2.m1()
c2.m2()

First Parent Method
Child Method
Second Parent Method
Child Method


### 5) Hybrid Inheritance:

Combination of Single, Multi level, multiple and Hierarchical inheritance is known as Hybrid Inheritance.<br>
<img src="images/Hybrid_Inheritance.png" width=300><br>
**Note:** In Hybrid Inheritance, method resolution is based on **MRO** algorithm.

### 6) Cyclic Inheritance:

The concept of inheriting properties from one class to another class in cyclic way, is called Cyclic inheritance. **Python won't support for Cyclic Inheritance, of course it is really not required.**<br>

In [18]:
# Example 1
class A(A):
    pass

NameError: name 'A' is not defined

<img src="images/cyclic_inheritance_1.png" width=300>

In [19]:
# Example 2
class A(B):
    pass
class B(A):
    pass

NameError: name 'B' is not defined

<img src="images/cyclic_inheritance_2.png" width=250>

# Method Resolution Order(MRO)

- In Hybrid Inheritance the method resolution order is decided based on MRO algorithm.<br>
- This algorithm is also known as C3 algorithm.<br>
- Samuele Pedroni proposed this algorithm.<br>
- It follows DLR (Depth First Left to Right) i.e Child will get more priority than Parent.<br>
- Left Parent will get more priority than Right Parent.<br>
- MRO(X) = X+Merge(MRO(P1),MRO(P2),...,ParentList)<br>

**Note:** We can find MRO of any class by using mro() function. <br>
&emsp;&emsp;&emsp;**print(ClassName.mro())**<br>
<img src="images/MRO_Demo1.png" width=600 align="left">

In [2]:
class A: pass
class B(A): pass
class C(A): pass
class D(B,C): pass
print(A.mro()) 
print(B.mro())
print(C.mro())
print(D.mro())

[<class '__main__.A'>, <class 'object'>]
[<class '__main__.B'>, <class '__main__.A'>, <class 'object'>]
[<class '__main__.C'>, <class '__main__.A'>, <class 'object'>]
[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>]


In [4]:
class A:
    def m1(self):
        print('A Class Method')
class B:
    def m1(self):
        print("B Class Method")
class C(A):
    def m1(self):
        print('C Class Method')
class D(B,C):
    def m1(self):
        print('D Class Method')
d=D() #DBCAO
d.m1() # since m1 is availble is D class, D class will be displayed as first priority.

D Class Method


In [5]:
class A:
    def m1(self):
        print('A Class Method')
class B:
    def m1(self):
        print("B Class Method")
class C(A):
    def m1(self):
        print('C Class Method')
class D(B,C):
    pass
d=D() #DBCAO
d.m1() # since m1 not available in D, next priority will be B

B Class Method


In [6]:
class A:
    def m1(self):
        print('A Class Method')
class B:
    pass
class C(A):
    def m1(self):
        print('C Class Method')
class D(B,C):
    pass
d=D() #DBCAO
d.m1() # since m1 not available in D,B next priority will be C

C Class Method


In [7]:
class A:
    def m1(self):
        print('A Class Method')
class B:
    pass
class C(A):
    pass
class D(B,C):
    pass
d=D() #DBCAO
d.m1() # since m1 not available in D,B,C next priority will be A.

A Class Method


In [8]:
class A:
    pass
class B:
    pass
class C(A):
    pass
class D(B,C):
    pass
d=D() #DBCAO
d.m1() # if m1 not availble in D,B,C,A then MRO will decide to check in Object. if Not Available, it will raise error.

AttributeError: 'D' object has no attribute 'm1'

In the above example, we have worked on only two levels which is straight forward to say the MRO. But there will be some cases where we will have multilevels. We need to understand how MRO will work in those multilevel cases.<br>Lets look at an example of how to do it.<br>
<img src="images/MRO_Demo2.png" align="left" width=700>

In [2]:
class A: pass
class B: pass
class C: pass
class X(A,B): pass
class Y(B,C): pass
class P(X,Y,C): pass
print(A.mro())
print(B.mro())
print(C.mro())
print(X.mro())
print(Y.mro())
print(P.mro())

[<class '__main__.A'>, <class 'object'>]
[<class '__main__.B'>, <class 'object'>]
[<class '__main__.C'>, <class 'object'>]
[<class '__main__.X'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]
[<class '__main__.Y'>, <class '__main__.B'>, <class '__main__.C'>, <class 'object'>]
[<class '__main__.P'>, <class '__main__.X'>, <class '__main__.A'>, <class '__main__.Y'>, <class '__main__.B'>, <class '__main__.C'>, <class 'object'>]


In [6]:
class A:
    def m1(self):
        print("Class A Method")
class B: 
    def m1(self):
        print("Class B Method")
class C:
    def m1(self):
        print("Class C Method")
class X(A,B):
    def m1(self):
        print("Class X Method")
class Y(B,C):
    def m1(self):
        print("Class Y Method")
class P(X,Y,C):
    def m1(self):
        print("Class P Method")

p=P()
p.m1() # since m1 is avaiable in P method, m1 from P class will be displayed.

Class X Method


In [7]:
class A:
    def m1(self):
        print("Class A Method")
class B: 
    def m1(self):
        print("Class B Method")
class C:
    def m1(self):
        print("Class C Method")
class X(A,B):
    def m1(self):
        print("Class X Method")
class Y(B,C):
    def m1(self):
        print("Class Y Method")
class P(X,Y,C):
    pass

p=P()
p.m1() # if m1 is not avaiable in P method,then MRO will prefer to check in X.

Class X Method


In [8]:
class A:
    def m1(self):
        print("Class A Method")
class B: 
    def m1(self):
        print("Class B Method")
class C:
    def m1(self):
        print("Class C Method")
class X(A,B):
    pass
class Y(B,C):
    def m1(self):
        print("Class Y Method")
class P(X,Y,C):
    pass

p=P()
p.m1() # if m1 is not avaiable in P,X method,then MRO will prefer to check in A.

Class A Method


In [9]:
class A:
    pass
class B: 
    def m1(self):
        print("Class B Method")
class C:
    def m1(self):
        print("Class C Method")
class X(A,B):
    pass
class Y(B,C):
    def m1(self):
        print("Class Y Method")
class P(X,Y,C):
    pass

p=P()
p.m1() # if m1 is not avaiable in P,X,A method,then MRO will prefer to check in Y.

Class Y Method


In [10]:
class A:
    pass
class B: 
    def m1(self):
        print("Class B Method")
class C:
    def m1(self):
        print("Class C Method")
class X(A,B):
    pass
class Y(B,C):
    pass
class P(X,Y,C):
    pass

p=P()
p.m1() # if m1 is not avaiable in P,X,A,Y method,then MRO will prefer to check in B.

Class B Method


In [11]:
class A:
    pass
class B: 
    pass
class C:
    def m1(self):
        print("Class C Method")
class X(A,B):
    pass
class Y(B,C):
    pass
class P(X,Y,C):
    pass

p=P()
p.m1() # if m1 is not avaiable in P,X,A,Y,B method,then MRO will prefer to check in C.

Class C Method


In [13]:
class A:
    pass
class B: 
    pass
class C:
    pass
class X(A,B):
    pass
class Y(B,C):
    pass
class P(X,Y,C):
    pass

p=P()
p.m1() # if m1 is not avaiable in P,X,A,Y,B,C method,then MRO will prefer to check in Object Class.
# Since object class doesn't contain m1() method, this will raise an attribute error.

AttributeError: 'P' object has no attribute 'm1'

In the above example P class m1() method will be considered.If P class does not contain m1() method then as per MRO, X class method will be considered. If X class does not contain then A class method will be considered and this process will be continued.<br><br>
The method resolution in the following order: **PXAYBCO**

As we have seen above, MRO Algorithm is making the order. Lets understand how MRO Algortihm internally works. It works with a formula as shown below.<br>
**MRO(X) = X+Merge(MRO(P1),MRO(P2),...,ParentList)**<br>
**Note:** Here we have to consider only immediate parents.<br><br>
## Head Element vs Tail Terminology: 
- Assume C1,C2,C3,...are classes. <br>
- In the list: C1C2C3C4C5.... <br>
- C1 is considered as Head Element and remaining is considered as Tail.<br>

## How to find Merge:
**Below are the steps to consider for findng the merge.**
- Take the head of first list<br>
- If the head is not in the tail part of any other list, then add this head to the result and remove it from the lists in the merge.<br> 
- If the head is present in the tail part of any other list, then consider the head element of the next list and continue the same process.<br><br>
Lets Understand how the MRO will decide the order with following example with above merge steps.<br>
<img src="images/MRO_Demo3.png" width=600 align="left">

**mro(o) = object**<br>
**mro(D) = D, object**<br>
**mro(E) = E, object**<br>
**mro(F) = F, object**<br>
**mro(B) = B, D, E, object**<br>
**mro(C) = C, D, F, object**<br>
**mro(A) = A + Merge(mro(B), mro(C), BC)** =========> B,C are the immediate parents of A. We already have made order for B,C<br> 

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + Merge(BDEO, CDFO, BC)** ========> mro(B)-BDEO, mro(C)-CDFO, ParentList BC will remain same. <br>

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + B + Merge(DEO, CDFO, C)** =========> B is the head of the First List(BDEO). DFO,C are the tails of list CDFO,BC. We need to check for head B in the other lists tails i.e in DFO,C. Since, B is Not Available in the tails. B will be Brought out by removing in the other lists i.e. removing B from BDEO and BC. After Removing we are left with Merge(DEO,CDFO,C). <br>

<br>Now we have First List as DEO where D is the head, Lets check if D is available in other lists tails. Yes D is available in DFO. So we should consider C as head of the list CDFO and check for C in Onter list tails. C is available in parent list, so lets remove C from CDFO and C. Add C to Result. Now we have Merge(DEO, DFO)<br><br>

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + B + C + Merge(DEO, DFO)** =======> head D from DEO is not available in tail FO of other list DFO. So Adding D to result and Removing from all lists.<br>

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + B + C + D + Merge(EO, FO)** ======> head E from EO is not available in tail O of FO list. Adding E to the Result and removing from all the list.<br>

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + B + C + D + E + Merge(O, FO)** ======> Since head O is available in tail of FO, F will be the head now. So search F in other lists tail. Since, Not Available, Adding E to the result and removing from lists.<br>

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + B + C + D + E + F + Merge(O, O)** =======> head O is not Available in any other lists tail, so adding O to result and removing from lists remaning. Thats it. So everything came out of the list and added to result.  <br>

**&emsp;&emsp;&emsp;&nbsp;&nbsp;= A + B + C + D + E + F + O** ======> This Final Result is the Order decided by MRO method for F.

In [14]:
class D:
    pass
class E:
    pass
class F:
    pass
class B(D,E):
    pass
class C(D,F):
    pass
class A(B,C):
    pass

print(D.mro())
print(E.mro())
print(F.mro())
print(B.mro())
print(C.mro())
print(A.mro())

[<class '__main__.D'>, <class 'object'>]
[<class '__main__.E'>, <class 'object'>]
[<class '__main__.F'>, <class 'object'>]
[<class '__main__.B'>, <class '__main__.D'>, <class '__main__.E'>, <class 'object'>]
[<class '__main__.C'>, <class '__main__.D'>, <class '__main__.F'>, <class 'object'>]
[<class '__main__.A'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.D'>, <class '__main__.E'>, <class '__main__.F'>, <class 'object'>]


Above order perfectly matched with program.<br>

This is all about Method Resolution Order (MRO) and its internal working specially for hybrid Inheritances. Hope you got good understanding with the above 3 demo exmaples.

# The Complete Story of super() Function

We know that all the funtionalities and methods of Parent Class are available to Child Class by Default, if child class in inherited with parent class like below.

In [15]:
class P:
    def m1(self):
        print("Parent Class")
class C(P):
    def m2(self):
        print("Child Class")
c=C()
c.m1() # accessing m1 method in parent class from child class
c.m2() # method m2 present in the child class

Parent Class
Child Class


In [16]:
class P:
    def m1(self):
        print("Parent Class")
class C(P):
    def m2(self):
        self.m1()
        print("Child Class")
c=C()
c.m2() # As a part of method m2 present in the child class, m1 from parent class will also be accesed automatically on calling m2

Parent Class
Child Class


For the above two examples, there is no problem.<br><br>
But the real problem arises, if we have methods with same name in both parent class and child class. Which from which class the method will be considered ?? <br> 

In [18]:
# if we call m1 method of child class and parent class from child class itself, this will lead to recursion error as below.
class P:
    def m1(self):
        print("Parent Class")
class C(P):
    def m1(self):
        self.m1()
        print("Child Class")
c=C()
c.m1()

RecursionError: maximum recursion depth exceeded

if both parent class method and child class method having the same naming conflict and ambiguity is there, then there must be some solution to avoid it.<br><br>
To differentiate Child Class Method and Parent class method, we have a special mechanism called **super()** Function.<br>
<br>From child class if you want to call parent class methods explicitly, super() function is very much useful.

In [19]:
class P:
    def m1(self):
        print("Parent Class")
class C(P):
    def m1(self):
        super().m1() # Now there will no issue, since m1 is called from Parent Class with super()
        print("Child Class")
c=C()
c.m1()

Parent Class
Child Class


## super() Method:
**super()** is a built-in method which is useful to call the super class constructors,variables and methods from the child class.

In [20]:
class P:
    a=10
    def __init__(self):
        print("Parent Constructor")
        
    def m1(self):
        print("Parent Instance Method")
        
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
class C(P):
    def __init__(self):
        print("Child Constructor")
    
    def method1(self):
        print(super().a)
        super().m1()
        super().m2()
        super().m3()
        super().__init__()
        
c=C()
c.method1()

Child Constructor
10
Parent Instance Method
Parent Class Method
Parent Static Method
Parent Constructor


In [21]:
# There is no naming conflict, so instead of super() we can use self.
class P:
    a=10
    def __init__(self):
        print("Parent Constructor")
        
    def m1(self):
        print("Parent Instance Method")
        
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
class C(P):
    def __init__(self):
        print("Child Constructor")
    
    def method1(self):
        print(self.a) # No Naming Conflict for 'a', We can use self insted od super()
        self.m1() # No Naming Conflict for 'm1', We can use self insted od super()
        self.m2() # No Naming Conflict for 'm2', We can use self insted od super()
        self.m3() # No Naming Conflict for 'm3', We can use self insted od super()
        super().__init__() # Here we need to use super() only instead of self. its because __init__ is avialble in both classes.
        # So to execute the parent class constructor super() should be used.
c=C()
c.method1()

Child Constructor
10
Parent Instance Method
Parent Class Method
Parent Static Method
Parent Constructor


In [22]:
# Example 3

class Person:
    def __init__(self,name,age,height,weight):
        self.name = name
        self.age = age
        self.height = height
        self.weight = weight
        
    def display(self):
        print("Name:",self.name)
        print("Age:",self.age)
        print("Height:",self.height)
        print("Weight:",self.weight)
        
class Student(Person):
    def __init__(self,name,age,height,weight,rollno,marks):
        self.name = name # Available in Parent Class (Person)
        self.age = age # Available in Parent Class (Person)
        self.height = height # Available in Parent Class (Person)
        self.weight = weight # Available in Parent Class (Person)
        self.rollno = rollno
        self.marks = marks
        
    def display(self):
        print("Name:",self.name) # Available in Parent Class (Person)
        print("Age:",self.age) # Available in Parent Class (Person)
        print("Height:",self.height) # Available in Parent Class (Person)
        print("Weight:",self.weight) # Available in Parent Class (Person)
        print("Rollno:",self.rollno)
        print("Marks:",self.marks)
        
s = Student("Sairam",25,5.10,'65 Kgs',263,100)
s.display()


Name: Sairam
Age: 25
Height: 5.1
Weight: 65 Kgs
Rollno: 263
Marks: 100


We are using only child class and parametrs to child class itself, No Parent class in used in above program. name,age,weight,height are the common Instance variables in both Parent(Person) and Child(Student) classes.

In [23]:
class Person:
    def __init__(self,name,age,height,weight):
        self.name = name
        self.age = age
        self.height = height
        self.weight = weight
        
    def display(self):
        print("Name:",self.name)
        print("Age:",self.age)
        print("Height:",self.height)
        print("Weight:",self.weight)
        
class Student(Person):
    def __init__(self,name,age,height,weight,rollno,marks):
        super().__init__(name,age,height,weight) # calling from parent class Person.
        self.rollno = rollno
        self.marks = marks
        
    def display(self):
        super().display() # calling from parent class Person.
        print("Rollno:",self.rollno)
        print("Marks:",self.marks)
        
s = Student("Sairam",25,5.10,'65 Kgs',263,100)
s.display()


Name: Sairam
Age: 25
Height: 5.1
Weight: 65 Kgs
Rollno: 263
Marks: 100


In the above code, we have super() to call the constructor from parent class itself and to get the parent class display method. Here we have obtained Code Reusability and Code Extendability.

## How to Call Method of a Particular Super Class: (Optional)

In [24]:
class A:
    def m1(self):
        print("A Class Method")
class B(A):
    def m1(self):
        print("B Class Method")
class C(B):
    def m1(self):
        print("C Class Method")
class D(C):
    def m1(self):
        print("D Class Method")
class E(D):
    def m1(self):
        print("E Class Method")
        
e = E()
e.m1() # Since m1 is available in E Class itslef, m1 is displayed.

E Class Method


In [25]:
class A:
    def m1(self):
        print("A Class Method")
class B(A):
    def m1(self):
        print("B Class Method")
class C(B):
    def m1(self):
        print("C Class Method")
class D(C):
    def m1(self):
        print("D Class Method")
class E(D):
    def m1(self):
        # Now i want to call m1 with super() method
        super().m1() # This will display the m1 from preceeding parent D

e = E()
e.m1()

D Class Method


But my requirement is, i don't to get m1 method from immediate Super class method. I want m1 method from the particular class.<br>
This is one important scenario.<br>Yes, We can call method from particular class as we required.<br><br>
We can use the following approaches<br>
1) <span style='color:orange'>**super(ClassName,self).MethodName()**</span> ===> **super(D, self).m1()** ==> It will call m1() method of super class of D. i.e m1 from C class will be executed<br>
2) <span style='color:orange'>**ClassName.MethodName(self)**</span> ===> **A.m1(self)** ==> It will call A class m1() method

In [27]:
class A:
    def m1(self):
        print("A Class Method")
class B(A):
    def m1(self):
        print("B Class Method")
class C(B):
    def m1(self):
        print("C Class Method")
class D(C):
    def m1(self):
        print("D Class Method")
class E(D):
    def m1(self):
        # Now i want to call m1 from B without super() method
        B.m1(self) # This will display the m1 from class B

e = E()
e.m1()

B Class Method


In [28]:
class A:
    def m1(self):
        print("A Class Method")
class B(A):
    def m1(self):
        print("B Class Method")
class C(B):
    def m1(self):
        print("C Class Method")
class D(C):
    def m1(self):
        print("D Class Method")
class E(D):
    def m1(self):
        # Now i want to call m1 from B without super() method
        D.m1(self) # This will display the m1 from class D

e = E()
e.m1()

D Class Method


In [29]:
class A:
    def m1(self):
        print("A Class Method")
class B(A):
    def m1(self):
        print("B Class Method")
class C(B):
    def m1(self):
        print("C Class Method")
class D(C):
    def m1(self):
        print("D Class Method")
class E(D):
    def m1(self):
        # Now i want to call m1 from C with super() method
        super(D, self).m1() # This will display the m1 from class C, Since C is the preceeding parent of D.

e = E()
e.m1()

C Class Method


# super() vs Instance Variables ( Optional)

In [31]:
class P:
    a=888
    def __init__(self):
        self.b = 999
        
class C(P):
    def m1(self):
        # we can happily access the a,b from Parent class P using self. No need to use super() since there is no naming conflict.
        print(self.a)
        print(self.b)
        
c=C()
c.m1()

888
999


In [32]:
class P:
    a=888
    def __init__(self):
        self.b = 999
        
class C(P):
    def m1(self):
        # we can happily access the a,b from Parent class P using self. No need to use super() since there is no naming conflict.
        #print(self.a)
        #print(self.b)
        # we can't use super to access parent class Instance Variable i.e self.b
        print(super().a) # this is perfectly valid, since it is static variable
        print(super().b) # This will raise an error, since super can't access Instance variable from Parent class 
c=C()
c.m1()

888


AttributeError: 'super' object has no attribute 'b'

**Note:** we can't use super() to access parent class Instance Variable, we should **self** to access it from the child class.

In [33]:
class P:
    a=888
    def __init__(self):
        self.b = 999
        
class C(P):
    def m1(self):
        print(super().a) # this is perfectly valid, since it is static variable
        print(self.b) # should  use only self to access Instance Variables from Parent Class.
c=C()
c.m1()

888
999


# Important conclusions of super() method ( Optional)

In [35]:
class P:
    a=10
    def __init__(self):
        print("Parent Constructor")
        
    def m1(self):
        print("Parent Instance Method")
        
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
class C(P):
    # from child constructor, we can call parent constructor,Instance,class,static methods. No problem at all
    def __init__(self):
        super().__init__() # valid
        super().m1()       # valid
        super().m2()       # valid
        super().m3()       # valid
        
    def m1(self): # Instance Method from Child Class
        # from child constructor, we can call parent constructor,Instance,class,static method
        super().__init__() # valid
        super().m1()       # valid
        super().m2()       # valid
        super().m3()       # valid
    
c=C()
c.m1()

Parent Constructor
Parent Instance Method
Parent Class Method
Parent Static Method
Parent Constructor
Parent Instance Method
Parent Class Method
Parent Static Method


<span style='color:brown'>**From child class constructor and instance methods, we can call parent class constructors, Instance methods, class methods and static methods by using super().**</span>

In [36]:
class P:
    a=10
    def __init__(self):
        print("Parent Constructor")
        
    def m1(self):
        print("Parent Instance Method")
        
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
class C(P):
    # from child constructor, we can call parent constructor,Instance,class,static methods. No problem at all
    def __init__(self):
        super().__init__() # valid
        super().m1()       # valid
        super().m2()       # valid
        super().m3()       # valid
        
    def m1(self): # Instance Method from Child Class
        # from child constructor, we can call parent constructor,Instance,class,static method
        super().__init__() # valid
        super().m1()       # valid
        super().m2()       # valid
        super().m3()       # valid
    
    @classmethod
    def m2(cls):
        super().__init__() # Not valid, This will raise an error. we can't use super() to call parent class-class method from child class-class method
        super().m1()       # Not valid, This will raise an error. we can't use super() to call parent class-Instance method from child class-Instance method
        super().m2()       # valid
        super().m3()       # valid
    

C.m2()

TypeError: __init__() missing 1 required positional argument: 'self'

<span style='color:brown'>**From child class-class method we cannot access parent class constructor and instance methods directly by using super() (But indirectly possible). But we can access parent class static and class methods.**</span><br><br>
**Reason:** <span style='color:blue'>**Class method is no way related to object. Without object also we ca call class method. But constructor and instance methods are always associated with object.**</span>

In [38]:
class P:
    a=10
    def __init__(self):
        print("Parent Constructor")
        
    def m1(self):
        print("Parent Instance Method")
        
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
class C(P):
    # from child constructor, we can call parent constructor,Instance,class,static methods. No problem at all
    def __init__(self):
        super().__init__() # valid
        super().m1()       # valid
        super().m2()       # valid
        super().m3()       # valid
        
    def m1(self): # Instance Method from Child Class
        # from child constructor, we can call parent constructor,Instance,class,static method
        super().__init__() # valid
        super().m1()       # valid
        super().m2()       # valid
        super().m3()       # valid
    
    @staticmethod
    def m3():
        super().__init__() # Not valid, this will raise an error
        super().m1()       # Not valid, this will raise an error
        super().m2()       # Not valid, this will raise an error
        super().m3()       # Not valid, this will raise an error
        
C.m3()

RuntimeError: super(): no arguments

<span style='color:brown'>**From child class static method, we cannot use super() to call parent class members. But indirectly we can call parent class static and class methods.**</span>

### From Class Method of Child Class, how to call Parent Class Instance Methods and Constructors indirectly:

In [39]:
class P:
    def __init__(self):
        print("Parent Constructor")
        
    def m1(self):
        print("Parent Instance Method")
        
class C(P):
    @classmethod
    def m2(cls):
        super(C,cls).__init__(cls) # calling constructor of parent class from class method of child class indirectly
        super(C,cls).m1(cls) # calling Instance method of parent class from class method of child class indirectly.
        

C.m2()

Parent Constructor
Parent Instance Method


### How to Call Parent Class Static Method from Child Class Static Method by using super() indirectly:

In [40]:
class P:
    @classmethod
    def m2(cls):
        print("Parent Class Method")
        
    @staticmethod
    def m3():
        print("Parent Static Method")
        
class C(P):
    @staticmethod
    def m2():
        super(C,C).m2() # Indirect method to call Parent class-class method from child class-static method
        super(C,C).m3() # Indirect method to call Parent class-Static method from child class-static method
        
C.m2()

Parent Class Method
Parent Static Method


# ========================== PART - 3 ===========================

# Polymorphism

**Poly** means **many**.<br>
**Morphs** means **forms**.<br>
**Polymorphism** means '**Many Forms**'.<br><br>**One Name but Multiple Forms is the concept of Polymorphism**<br><br>
**More Flexibility is the advantage of Polymorphissm**<br><br>
**Eg1:** Yourself is best example of polymorphism. In front of Your parents You will have one type of behaviour and with friends another type of behaviour. Same person but different behaviours at different places,which is nothing but polymorphism.<br>
**Eg2:** + operator acts as concatenation and arithmetic addition (Operator Overloading)<br>
**Eg3:** * operator acts as multiplication and repetition operator (Operator Overloading)<br>
**Eg4:** The Same method with different implementations in Parent class and child classes.(Method overriding)<br><br>Example:


In [1]:
class P: # subbalaxmi/appalama are the brides which parents have chosen for groom. But child is not satisfiess with thier selection.
    def marry(self):
        print("SubbaLaxmi/Apalama")
        
class C(P): # But groom want to marry a bride with name Katrina kaif. So he is redifining the bride for this marriage, since he is not satisfied. 
    def marry(self):
        print("Kartina Kaif") # This Type of redefining the same method with different implementations is called as method overriding.
        
c=C()
c.marry()


Kartina Kaif


Related to Polymorphism the following topics are important<br><br>

**1) Overloading**<br>
> 1) Operator Overloading <br>
> 2) Method Overloading<br>
> 3) Constructor Overloading<br>

**2) Overriding**<br>
> 1) Method Overriding<br>
> 2) Constructor Overriding<br>

**3) Pythonic Behavior**<br>
> - Duck Typing Philosophy of Python<br>
> - Easier to Ask Forgiveness than Permission(EAFP)<br>
> - Monkey Patching<br>

### 1) Overloading

We can use same operator or methods for different purposes.<br>
**Eg 1:** + operator can be used for Arithmetic addition and String concatenation<br>
> print(10+20) # 30<br>
> print('durga'+'soft') # durgasoft<br>

**Eg 2:** * operator can be used for multiplication and string repetition purposes.<br>
> print(10*20) # 200<br>
> print('durga'*3) # durgadurgadurga<br>

**Eg 3:** We can use deposit() method to deposit cash or cheque or dd<br>
> deposit(cash)<br>
> deposit(cheque)<br>
> deposit(dd)<br>

**There are 3 types of Overloading** <br><br>
1) Operator Overloading<br>
2) Method Overloading <br>
3) Constructor Overloading<br>


### 1) Operator Overloading:
- We can use the same operator for multiple purposes, which is nothing but operator overloading.<br> 
- Python supports operator overloading.<br><br>

**Eg 1:** + operator can be used for Arithmetic addition and String concatenation<br>

In [2]:
print(10+20) #30
print('durga'+'soft') #durgasoft

30
durgasoft


**Eg 2:** * operator can be used for multiplication and string repetition purposes.<br>

In [3]:
print(10*20) # 200
print('durga'*3) # durgadurgadurga

200
durgadurgadurga


In [4]:
# Demo program to use + operator for our class objects:

class Book:
    def __init__(self,pages):
        self.pages = pages
        
b1=Book(100)
b2=Book(200)
print(b1+b2) # tough python supports operator overloading, we will get error.
# we need to use some special methods to perfom operator overaloading.

TypeError: unsupported operand type(s) for +: 'Book' and 'Book'

⚽ We can overload + operator to work with Book objects also. i.e Python supports Operator Overloading.<br> 
⚽ For every operator Magic Methods are available. To overload any operator we have to override that Method in our class.<br>
⚽ Internally + operator is implemented by using __add__() method.This method is called magic method for + operator. We have to override this method in our class.

Whenever we are using + operator between two book objects, immediately Python Vitual machine will check whether the book class contain corressponding magic method or not.<br>

**So if you want to use any operator between two objects, compulsarily we need to define respective magic method of the operator.**

In [5]:
class Book:
    def __init__(self,pages):
        self.pages = pages
        
    def __add__(self,other): # Magic method
        total_pages = self.pages + other.pages
        return total_pages
        
        
b1=Book(100)
b2=Book(200)
print(b1+b2) # b1 will pass to self and b2 will pass to other arguments.

300


In [6]:
b1=Book(100)
b2=Book(200)
b3=Book(300)
print(b1+b2) # b1 will pass to self and b2 will pass to other arguments.
print(b1+b3)
print(b2+b3)

300
400
500


In [7]:
# b1+b2, b1+b3, b2+b3 worked fine No isuues. But can we perform b1+b2+b3 with above code.
print(b1+b2+b3)

TypeError: unsupported operand type(s) for +: 'int' and 'Book'

We will discuss about this issue at last.

The following is the list of operators and corresponding magic methods.<br>
<img src="images/magic_methods.png" width = 400 align='left'>

#### Overloading > and <= Operators for Student Class Objects:

In [9]:
class Student:
    def __init__(self,name,marks):
        self.name = name
        self.marks = marks
        
s1=Student("Sairam",100)
s2=Student("Dhana",95)
print(s1 > s2) # This will raise error, since it will expect some magic method.

TypeError: '>' not supported between instances of 'Student' and 'Student'

In [48]:
class Student:
    def __init__(self,name,marks):
        self.name = name
        self.marks = marks
        
    def __gt__(self,other): # Greater Than Magic Method
        return self.marks > other.marks
        
    def __le__(self,other):
        return self.marks<=other.marks
    
s1=Student("Sairam",100)
s2=Student("Dhana",95)
s3=Student("Prasad",97)
print(s1 > s2) # True 
print(s2 > s3) # False
print(s2 < s3) 
# True, We can define magic method either for less than or greater then only, it will reverse as needed.
print(s2 <= s3)
print(s1 >= s2)

True
False
True
True
True


#### Program to Overload Multiplication Operator to Work on Employee Objects:

In [1]:
class Employee:
    def __init__(self,name,SalaryPerDay):
        self.name = name
        self.SalaryPerDay = SalaryPerDay
        
class TimeSheet:
    def __init__(self,name,workingdays):
        self.name = name
        self.workingdays = workingdays

e=Employee('Sairam',1000)
t=TimeSheet('Sairam',25)
print("This Month Salary:",e*t) # should implement magic method 

TypeError: unsupported operand type(s) for *: 'Employee' and 'TimeSheet'

In [3]:
class Employee:
    def __init__(self,name,SalaryPerDay):
        self.name = name
        self.SalaryPerDay = SalaryPerDay
    def __mul__(self,other):
        return self.SalaryPerDay*other.workingdays
        
class TimeSheet:
    def __init__(self,name,workingdays):
        self.name = name
        self.workingdays = workingdays
    def __mul__(self,other):
        return self.workingdays*other.SalaryPerDay

e=Employee('Sairam',1000)
t=TimeSheet('Sairam',25)
print("This Month Salary:",e*t) # implemented magic method in Employee class because of the multiplication order.
print("This Month Salary:",t*e) # order is very impoortant, so to perform this multiplication also, need to implement magic method.

This Month Salary: 25000
This Month Salary: 25000


### Importance of \_\_str\_\_() method

In [4]:
class Student:
    def __init__(self,name,rollno,marks):
        self.name = name
        self.rollno = rollno
        self.marks = marks
        
s1=Student('Sairam',263,100)
s2=Student('Ravi',264,95)
print(s1) # Inertnally __str__() method will be executed, if not given explicitly
print(s2) # Inertnally __str__() method will be executed, if not given explicitly. 

whenever we are trying to print object reference, internally \_\_str\_\_() method will be called.<br><br>
The default implementation of this method returns the string in the following format:<br>
> <__main__.Student object at 0x000001CE10CABFA0>

To Provide meaningful string reperesentation for our object, we have to override \_\_str\_\_() method in our class.

We dont need the output as above, we are expecting the meaningful information given. We need to implement \_\_str\_\_() in our class like below.

In [7]:
class Student:
    def __init__(self,name,rollno,marks):
        self.name = name
        self.rollno = rollno
        self.marks = marks
    
    def __str__(self): # Magic Method
        return 'Name:{}, RollNo:{}, Marks:{}'.format(self.name,self.rollno,self.marks)
    
s1=Student('Sairam',263,100)
s2=Student('Ravi',264,95)
print(s1) # since we have override the internal __str__() method by magic method __str__(), this will give the info as required.
print(s2)  

Name:Sairam, RollNo:263, Marks:100
Name:Ravi, RollNo:264, Marks:95


### Overloading of + operator for nesting Requirements

previously as discussed we can perform b1+b2+b3 like below.

In [8]:
class Book:
    def __init__(self,pages):
        self.pages = pages
        
    def __add__(self,other): # Magic method
        total_pages = self.pages + other.pages
        return total_pages
        
        
b1=Book(100)
b2=Book(200)
b3=Book(500)

print(b1+b2) # since we implmented magic method, this will work fine.
print(b1+b3) # since we implmented magic method, this will work fine.
print(b2+b3) # since we implmented magic method, this will work fine.

300
600
700


In [9]:
print(b1+b2+b3)

TypeError: unsupported operand type(s) for +: 'int' and 'Book'

As seen above, magic method accepts only two arguments, so we can't give extra arguments. Hence, b1+b2 will be calculated as 300 and is added to b3 like 300(integer)+b3(object). So the above error is raised due to unsupported operand types. if both are book objects only, then there will be no issue. 

In [16]:
class Book:
    def __init__(self,pages):
        self.pages = pages
        
    def __add__(self,other): # Magic method 
        return Book(self.pages + other.pages)
    
    def __str__(self):
        return 'The total no. of pages: {}'.format(self.pages)

b1=Book(100)
b2=Book(200)
b3=Book(500)
b4=Book(600) # we can add any number of book objects.
print(b1+b2+b3+b4) # Internally __str__() will be called, since we are adding 3 book objects and result will be an book object only.

The total no. of pages: 1400


In [20]:
class Book:
    def __init__(self,pages):
        self.pages = pages
        
    def __add__(self,other): # Magic method 
        print('Add executed')
        return Book(self.pages + other.pages)
    
    def __str__(self):
        return 'The total no. of pages: {}'.format(self.pages)
    def __mul__(self,other):
        print('Mul executed')
        return Book(self.pages*other.pages)

b1=Book(100)
b2=Book(200)
b3=Book(500)
b4=Book(600) # we can add any number of book objects.
print(b1+b2*b3+b4) #Operater precedence is followed

Mul executed
Add executed
Add executed
The total no. of pages: 100700


# Method Overloading

- If 2 methods having same name but different type of arguments then those methods are said to be overloaded methods.<br>
> **Eg:** m1(int a) <br>&emsp;&ensp;&nbsp;m1(double d)<br>

- But in Python Method overloading is not possible.<br>
- If we are trying to declare multiple methods with same name and different number of arguments then Python will always consider only last method.

In [1]:
class Test:
    def m1(self): # Won't be consdered
        print("No Arg Method")
    def m1(x,self): # Won't be Considered
        print("One Arg Method")
    def m1(x,y,self): # Since Only Last Method is considered if methods with same name are available, this will be executed.
        print("Two Arg Method")
        
t=Test()
t.m1() # This is proof that Last method will be considered. This will raise an error saying 2 arguments(x,y) are missing.

TypeError: m1() missing 2 required positional arguments: 'y' and 'self'

In [2]:
class Test:
    def m1(self): # Won't be consdered
        print("No Arg Method")
    def m1(self,x): # Won't be Considered
        print("One Arg Method")
    def m1(self,x,y): # Since Only Last Method is considered if methods with same name are available, this will be executed.
        print("Two Arg Method")
        
t=Test()
t.m1(10,20) # This is proof that Last method will be considered. This will Execute m1(self,x,y)

Two Arg Method


### Why Python won't support Method Overloading

In Java, we can declare type explicitly. But in python type we cannot declare type explicitly.<br>
Based on provided value type will be considered automatically(dynamically typed).<br> As Type Concept is not applicable, method overloading concept is also not available in python. 

**Python won't need Method Overloading concept, because we can do it with one single method as required.**<br> For example, we don't need to declare same methods with different arguments like in java, only one method is enough to do that for us as below. 

In [4]:
class Test:
    def m1(self,x):
        print("{}-Argument Method".format(x.__class__.__name__))
        
t=Test()
t.m1(10)
t.m1(10.5)
t.m1("Sairam")

int-Argument Method
float-Argument Method
str-Argument Method


### How to define a method with variable number of arguments

Most of the times, if method with variable number of arguments required then we can handle with **default arguments** or with **variable number of argument methods**.<br><br>
#### Demo Program with Default Arguments:

In [5]:
class Test:
    def m1(self,a=None,b=None,c=None):
        if a is not None and b is not None and c is not None:
            print('Three Argument Method')
        elif a is not None and b is not None:
            print('Two Argument Method')
        elif a is not None:
            print('One Argument Method')
        else:
            print("No Argument Method")
            
t=Test()
t.m1() # Not Argument Method
t.m1(10)
t.m1(10,20)
t.m1(10,20,30)

No Argument Method
One Argument Method
Two Argument Method
Three Argument Method


In [6]:
t.m1(10,20,30,40) # error willl be raised because arguments limited to 4(including self) but we have given 5.

TypeError: m1() takes from 1 to 4 positional arguments but 5 were given

To give any number of arguments we need we can do it as follows<br>
#### Demo Program with Variable Number of Arguments:

In [7]:
class Test:
    def m1(self,*args):
        print("Variable Lenght Arguments Method")

t=Test()
t.m1()
t.m1(10)
t.m1(10,20)
t.m1(10,20,30)
t.m1(10,20,30,40,50,60)

Variable Lenght Argument Method
Variable Lenght Argument Method
Variable Lenght Argument Method
Variable Lenght Argument Method
Variable Lenght Argument Method


In [9]:
# Program to add any number of values given

class Test:
    def sum(self,*args): # internally *args will be coverted to tuple
        total = 0
        for i in args:
            total = total+i
        print("The Sum:",total)
t=Test()
t.sum()
t.sum(10,20,30)
t.sum(40,50,60,70)


The Sum: 0
The Sum: 60
The Sum: 220


# 3) Constructor Overloading: 
⚽ Constructor overloading is not possible in Python.<br>
⚽ If we define multiple constructors then the last constructor will be considered.

In [4]:
class Test:
    def __init__(self): # This won't be considered
        print("No Arg Constructor")
    def __init__(self,x): # This won't be considered
        print("One Arg Constructor")
    def __init__(self,x,y): # Only the last constructor method will be considered. 
        print("Two Arg Constructor")
        
#t=Test() # This will raise error, since only last constructor method is considered it will expect two arguments
#t=Test(10) # This will raise error, since only last constructor method is considered it will expect two arguments
t=Test(10,20) # This will execute fine, two arguments are given as needed for the Last Constructor Method

Two Arg Constructor


- In the above program only Two-Arg Constructor is available.<br>
- But based on our requirement we can declare constructor with default arguments and variable number of arguments.

### Constructor with Default Arguments:

In [6]:
class Test:
    def __init__(self,a=None,b=None,c=None):
        print("Constructor with 0|1|2|3 arguments")
        
t=Test()
t=Test(10)
t=Test(10,20)
t=Test(10,20,30)

Constructor with 0|1|2|3 arguments
Constructor with 0|1|2|3 arguments
Constructor with 0|1|2|3 arguments
Constructor with 0|1|2|3 arguments


### Constructor with Variable Number of Arguments:

In [7]:
class Test:
    def __init__(self,*args):
        print("Constructor with variablle Number of arguments")
        
t=Test()
t=Test(10)
t=Test(10,20)
t=Test(10,20,30)
t=Test(10,20,30,40)

Constructor with variablle Number of arguments
Constructor with variablle Number of arguments
Constructor with variablle Number of arguments
Constructor with variablle Number of arguments
Constructor with variablle Number of arguments


# Overloading Methods support
<img src="images/Overloading_Support.png" width=700>

# 3) Overriding
### Method Overriding<br>
⚽ What ever members available in the parent class are bydefault available to the child class through inheritance. If the child class not satisfied with parent class implementation then child class is allowed to redefine that method in the child class based on its requirement. This concept is called overriding.<br>
⚽ Overriding concept applicable for both methods and constructors.

In [1]:
class Parent: #These are the things parent has defined to child class.
    def Property(self): # Child Very happy with these things
        print("Land+Gold+Cash+Power")
    def marry(self): # Child not satisfied with marriage with the girl named "Appalamma"
        print("Appalamma")
        
class Child(Parent): # Since he is not satisfied, he want to define the girl whom he want to marry.
    pass

c=Child()
c.Property()
c.marry()

Land+Gold+Cash+Power
Appalamma


In [2]:
class Parent: #These are the things parent has defined to child class.
    def Property(self): # Child Very happy with these things
        print("Land+Gold+Cash+Power")
    def marry(self): # Since this method is overridden by Child, This is Called Overridden Method
        print("Appalamma")
        
class Child(Parent):
    def marry(self): # Since, Child is redefining the parent method. This is called overriding method.
        print("Katrina Kaif")

c=Child()
c.Property() # This will come from Parent Class itself.
c.marry() # This will get the mary method from child class since it is already having it.

Land+Gold+Cash+Power
Katrina Kaif


From child class method we can also call parent class method using a sepcial method called super() method.

In [3]:
class Parent: 
    def Property(self): 
        print("Land+Gold+Cash+Power")
    def marry(self): 
        print("Appalamma")
        
class Child(Parent):
    def marry(self):
        super().marry() # We can get parent class marry method also with super()
        print("Katrina Kaif")

c=Child()
c.Property()
c.marry()

Land+Gold+Cash+Power
Appalamma
Katrina Kaif


### Constructor Overriding

In [5]:
class Parent:
    def __init__(self):
        print("Parent Constructor")
        
class Child(Parent):
    pass
    
c=Child() # Since Child class constructor is not Available, already available parent class constructor will be executed.


Parent Constructor


In [6]:
# if not satisfied with Parent Class Constructor, we can redefine the constructor it in Child class.
class Parent:
    def __init__(self):
        print("Parent Constructor")
        
class Child(Parent):
    def __init__(self):
        print("Child Constructor")
    
c=Child() #Child Class constructor will override the parent class constructor.

Child Constructor


In [7]:
# We can call Parent Class Constructor from Child CLass Constructor with special method.
class Parent:
    def __init__(self):
        print("Parent Constructor")
        
class Child(Parent):
    def __init__(self):
        super().__init__()
        print("Child Constructor")
    
c=Child() # Both Parent and Child Class Constructor will be executed

Parent Constructor
Child Constructor


### Overriding Demo Program

In [1]:
class Person:
    def __init__(self,name,age,height,weight):
        self.name = name
        self.age = age
        self.height = height
        self.weight = weight
        
    def display(self):
        print("Name:",self.name)
        print("Age:",self.age)
        print("Height:",self.height)
        print("Weight:",self.weight)
        
class Employee(Person):
    def __init__(self,name,age,height,weight,eno,esal):#Overriding the parent constructor
        self.name = name      
        self.age = age
        self.height = height
        self.weight = weight
        self.eno = eno
        self.esal = esal
        
    def display(self): #Overriding the Parent display method
        print("Name:",self.name)
        print("Age:",self.age)
        print("Height:",self.height)
        print("Weight:",self.weight)
        print("Employee Number:",self.eno)
        print("Employee Salary:",self.esal)
        
e=Employee("Sairam",48,5.9,65,55815,25000)
e.display()

Name: Sairam
Age: 48
Height: 5.9
Weight: 65
Employee Number: 55815
Employee Salary: 25000


In [3]:
class Person:
    def __init__(self,name,age,height,weight):
        self.name = name
        self.age = age
        self.height = height
        self.weight = weight
        
    def display(self):
        print("Name:",self.name)
        print("Age:",self.age)
        print("Height:",self.height)
        print("Weight:",self.weight)
        
class Employee(Person):
    def __init__(self,name,age,height,weight,eno,esal):
        # super() is responsible for creating the Instance Variables in child class by calling the Constructor from Parent class.
        super().__init__(name,age,height,weight) #Instead of rewriting again, we can use super function to get the things done from parent class itlsef. 
        self.eno = eno # New Inst
        self.esal = esal
        
    def display(self):
        # super() is responsible for diplay the first 4 properties of parent class display method in child class by calling the display method from Parent class..
        super().display()
        print("Employee Number:",self.eno)
        print("Employee Salary:",self.esal)
        print()
        
e=Employee("Sairam",25,5.9,65,55815,25000)
e.display()
e1=Employee("Dhana",21,5.2,40,55816,10000)
e1.display()

Name: Sairam
Age: 25
Height: 5.9
Weight: 65
Employee Number: 55815
Employee Salary: 25000

Name: Dhana
Age: 21
Height: 5.2
Weight: 40
Employee Number: 55816
Employee Salary: 10000



**super() will reduce lenght of the code and improve code readability.**<br><br>
<img src="images/polymorphism_summary.png" width=700>

# ========================== PART - 4 ==========================

## Abstraction

To understand Abstraction we need to know the following:<br>
> 1) Abstract Method<br>
> 2) Abstract Class<br>
> 3) Interface<br>

In general terms, Abstarction means something which is not having completeness. For Example<br>
**Project Abstract:** This always talks about the outline of the project, Complete Info about the implementation will not be given.<br>

#### Abstract Method:

- Sometimes we don't know about implementation, still we can declare a method. Such types of methods are called abstract methods.i.e abstract method has only declaration but not implementation.<br>
- In python we can declare abstract method by using **@abstractmethod** decorator as follows.<br>
> **@abstractmethod**<br>
> **def m1(self): pass**

For suppose i have to return the no. of tyres based on the vechile. Now i have the pupose, but i don't know which type of vechile it is so can't return anything just for now. So i have only declaration but no implementation. Such type of methods are called Abstract Methods. <br><br>

- @abstractmethod decorator is present in abc module. Hence compulsory we should import abc module,otherwise we will get error.<br> 
- abc ==> abstract base class module

In [ ]:
class Vechile:
    
    @abstractmethod
    def get_no_of_tyres(self):
        pass

In [8]:
from abc import abstractmethod

class Vechile:
    
    @abstractmethod
    def get_no_of_tyres(self):
        pass # since we are not in a position to present implementation, passing for now
    

**Child classes are responsible to provide implemention for parent class abstract methods.**

### Abstract class: 
Some times implementation of a class is not complete,such type of partially implementation classes are called **abstract classes**. <br><br>
Every abstract class in Python should be derived from ABC class which is present in abc module.<br>
ABC ===> Abstarct Base Class

In [11]:
from abc import *

class Vechile(ABC): # Abstract class since it is partially implemented
    
    # @abstractmethod is declared, then compulsary every child class should provide implemention to Parent Class.
    # if removed @abstractmethod, then it is not a abstract method. so child no need to provide implementation.
    @abstractmethod #declaring abstarct method with decorator
    def get_no_of_tyres(self):
        pass
    
class Bus(Vechile):
    def get_no_of_tyres(self):
        return 6
    
class Auto(Vechile):
    def get_no_of_tyres(self):
        return 3
    
b=Bus()
print(b.get_no_of_tyres())
a=Auto()
print(a.get_no_of_tyres())

6
3


**What is th advantage of declaring abstarct methods in Parent class?**<br>
- By declaring abstarct methods in parent class we can provide guidelines to the child classes, such that which method compulsarily the child classes should implement. <br>In the above example, **get_no_of_tyres** is declared with abstractmethod decorator in parent class so definitely, child classes Bus and Auto has to provide implementation as above.

In [13]:
from abc import *

class Vechile(ABC): # Abstract class since it is partially implemented
    
    # @abstractmethod is declared, then compulsary every child class should provide implemention to Parent Class.
    @abstractmethod
    def get_no_of_tyres(self):
        pass
    
class Bus(Vechile):
    pass

b=Bus() # This will raise an error, since child class is not providing the implementation tough the @abstarctmethod is declared.


TypeError: Can't instantiate abstract class Bus with abstract methods get_no_of_tyres

In [12]:
from abc import *

class Vechile(ABC): # this is Abstract class, since it is partially implemented
    
    
    # if removed @abstractmethod, then it is not a abstract method. so child no need to provide implementation.
    
    def get_no_of_tyres(self):
        pass
    
class Bus(Vechile):
    pass

b=Bus() # No error will be raised, since there is no abstarct method decorator in parent class. child can implement or maynot implement doesn't matter.


### Important Conclusions of Abstract Method and Abstract Class

In [1]:
class Test:
    pass

t=Test()

In the above code we can create object for Test class b'z it is concrete class and it does not conatin any abstract method.

In [2]:
from abc import *
class Test(ABC):
    pass

t=Test() # Object creation is still possible even after extending from ABC Module, because no abstract method is declared.

In the above code we can create object, even it is derived from ABC class,b'z it does not contain any abstract method.<br><br>
**Note:** An Abstarct class can contain zero number of abstract methods also.

In [3]:
from abc import *
class Test(ABC):
    @abstractmethod
    def m1(self):
        pass
    
t=Test()

TypeError: Can't instantiate abstract class Test with abstract methods m1

In the above code we can't create object if Abstract class is extended with ABC and if it contain abstract method.<br>
Because, we can't create an object partially implemented

In [5]:
from abc import *
class Test:
    @abstractmethod
    def m1(self):
        pass
    
t=Test()

We can create object even class contains abstract method b'z we are not extending ABC class.

In [6]:
from abc import *
class Test:
    @abstractmethod
    def m1(self):
        print("Hello")
    
t=Test()
t.m1()

Hello


**Conclusion:** <br>
If a class contains atleast one abstract method and if we are extending ABC class then instantiation is not possible.<br>
"abstract class with abstract method instantiation is not possible"<br><br>
Parent class abstract methods should be implemented in the child classes. Otherwise we cannot instantiate child class.If we are not creating child class object then we won't get any error.

In [7]:
from abc import *
class Test(ABC):
    @abstractmethod
    def m1(self):
        pass
    
class SubTest(Test):
    pass

t=SubTest() # Error will be raised 
# Since Child class doesn't contain any implementation for parent class abstract method, hence object creation is not possible

TypeError: Can't instantiate abstract class SubTest with abstract methods m1

In [8]:
from abc import *
class Test(ABC):
    @abstractmethod
    def m1(self):
        pass
    
    @abstractmethod
    def m2(self):
        pass
    
class SubTest(Test):
    def m1(self):
        print("m1 method implementation")
        
s = SubTest()
s.m1()
# we have declared two abstract methods in parent class, so implementation should be provided for both the methods.
# Since we have provided implementation only for m1 and not for m2, Error will be raised.

TypeError: Can't instantiate abstract class SubTest with abstract methods m2

In [9]:
from abc import *
class Test(ABC):
    @abstractmethod
    def m1(self):
        pass
    
    @abstractmethod
    def m2(self):
        pass
    
class SubTest(Test):
    def m1(self):
        print("m1 method implementation")
        
    def m2(self):
        print("m2 method implementation")

s = SubTest()
s.m1()
s.m2()
# This will work fine since implementation provided for both m1 and m2 methods.

m1 method implementation
m2 method implementation


If we provide implementation for every abstract method of parent class, then the child class will become concrete class and we can create objects and we can call the methods.

In [10]:
from abc import *

# An Abstarct Class can contain, both abstract methods and non-abstract methods also.
# Child Class is responsible for providing implementation to abstarct method in parent class.
class Test(ABC):
    # Non- Abstract method
    def m1(self):
        print("Non-Abstract Method")
    
    # Abstarct Method, Child is responsible for providing implementation only for m2 method.
    @abstractmethod
    def m2(self):
        pass
    
class SubTest(Test):
        
    def m2(self):
        print("m2 method implementation")

s = SubTest()
s.m1()
s.m2()

Non-Abstract Method
m2 method implementation


<span style="color:red">**Can a class contain both abstract and non-abstract methods ?**</span><br>
**Ans:** Yes<br>
**Note:** If a class contains both abstract and non-abstract methods then child class is responsible to provide implementation only for abstact methods. Otherwise, child class will be abstract and will not be able to create objects.

## Interfaces In Python:<br>
In general if an abstract class contains only abstract methods such type of abstract class is considered as interface.<br><br>
100% pure abstract class in nothing but interface.<br><br>
Interface simply acts as Service Requirement Specification(SRS).

In [11]:
class Test(ABC): 
    def m1(self):
        print("Hi")
        
    @abstractmethod
    def m2(self):
        pass
    
# This is just and abstract class not an interface since both abstract and non-abstarct methods are present.

In [14]:
class Test(ABC):
    @abstractmethod
    def m1(self):
        pass
    
    @abstractmethod
    def m2(self):
        pass

# This is an Interface, since both are abstarct methods in abstract class.

### What is the purpose of Interface ?

For example: One client came and said that he want an college automation sysem with the following services.<br>

**CollegeAutomationSystem:**<br>
> - getStudentAttendance()<br>
> - updateStudentAttendance()<br>
> - getMarks()<br>
> - updateMarks()<br>
> - getFeeInfo()<br>
> - updateFeeInfo()<br><br>

At the Top Level, we are simply collecting the requirements and creating an Interface i.e an Abstarct Class and respective Abstact methods.<br>
Some Low Level developers are responsible for providing implementation to these abstact methods.


In [15]:
# Lets understand with example
from abc import *

class CollegeAutomationSystem(ABC):
    @abstractmethod
    def m1(self):
        pass
    @abstractmethod
    def m2(self):
        pass
    @abstractmethod
    def m3(self):
        pass

# Above is the requirement, so any other developers can implement for us.
# lets say SmartCode is the company cameup to implement code for above requirements.

class SmartCode(CollegeAutomationSystem):
    def m1(self):
        print("m1 method")
    def m2(self):
        print("m2 method")
    def m3(self):
        print("m3 method")
        
d = SmartCode()
d.m1()
d.m2()
d.m3()

m1 method
m2 method
m3 method


In [16]:
# Example 2

from abc import *

class DBInterface(ABC):
    @abstractmethod
    def connect(self):pass
    
    @abstractmethod
    def disconnect(self):pass
    
class Oracle(DBInterface):
    def connect(self):
        print("Connecting to Oracle Database....")
    def disconnect(self):
        print("Disconnecting to Oracle Database....")
        
class Sybase(DBInterface):
    def connect(self):
        print("Connecting to Sybase Database....")
    def disconnect(self):
        print("Disconnecting to Sybase Database....")

        
dbname = input("Enter Database Name:")
classname = globals()[dbname]
x=classname()
x.connect()
x.disconnect()

Enter Database Name:Oracle
Connecting to Oracle Database....
Disconnecting to Oracle Database....


## Concreate class vs Abstract Class vs Inteface:
1) If we dont know anything about implementation just we have requirement specification then we should go for **interface**. <br>
> **Example:** we have a plan for building 100 floors building in 10 Years. This plan is example for **Interface****

2) If we are talking about implementation but not completely then we should go for **abstract class**. (partially implemented class). <br>
> **Example:** after 5 years only 75 floors are built 25 floors are still remaining. This building is partially implemented for the same 100 Floors plan . This is example for **Abstract Class**

3) If we are talking about implementation completely and ready to provide service then we should go for **concrete class**.<br>
> **Example:** after 10 Years, Building is completly ready as per the required plan. This is example for **Concrete Class**

In [18]:
from abc import *

class Interface(ABC):
    @abstractmethod
    def m1(self):
        pass
    @abstractmethod
    def m2(self):
        pass
    @abstractmethod
    def m3(self):
        pass


class AbstractClass(CollegeAutomation):
    def m1(self):
        print("m1 method implementation")
    def m2(self):
        print("m2 method implementation")
        
class ConcreteClass(AbstractClass):
    def m3(self):
        print("m3 method implementation")
        
d = ConcreteClass()
d.m1()
d.m2()
d.m3()

m1 method implementation
m2 method implementation
m3 method implementation


# Public, Protected and Private Attributes:

### Public Members
By default every attribute or method is public. We can access from anywhere either within the class or from outside of the class.<br>
**Eg:** name = 'durga'

In [21]:
class Test:
    def __init__(self):
        self.x=10 # By default this Instance variable is public
        
    def m1(self): # By default method is a public method
        print("Public Method")
        
    def m2(self):
        print(self.x) # Accessing public member x within the class
        self.m1() # accessing public method within the class
        
t=Test()
t.m2()
print(t.x) # Aceesing from outside of the class
t.m1() # Accesng method from outside of class

10
Public Method
10
Public Method


### Private Members

private attributes can be accessed only within the class.i.e from outside of the class we cannot access. We can declare a variable as private explicitly by prefexing with 2 underscore symbols.<br>
**Syntax:** \_\_variablename=value

In [25]:
class Test:
    def __init__(self):
        self.__x = 10 # Private Variable
        
    def __m1(self): # Private Method
        print("It is Private Method")
        
    def m2(self):
        print(self.__x) # Accessing private member x within the class
        print(self.__m1) # accessing private method within the class
        
t=Test()
t.m2() #m2 is a public method, we can call it from outside
print(t.__x) # Will raise an error, since it is an private member.it cannot be accessed from outside.

10
<bound method Test.__m1 of <__main__.Test object at 0x0000014523BE57F0>>


AttributeError: 'Test' object has no attribute '__x'

In [26]:
t.__m1() # Will raise an error, since it is an private method. it cannot be accessed from outside.

AttributeError: 'Test' object has no attribute '__m1'

### How to Access Private Variables from Outside of the Class:
We cannot access private variables directly from outside of the class. <br>
But we can access indirectly as follows **objectreference._classname__variablename**<br><br>

Name Mangling will be happened for the private variables. Hence every private variable name will be changed to new name.<br>
**\_\_VariableName ====> \_ClassName__VariableName**<br><br>
Hence we can access private variable fom outside of the class as follows:<br>
print(objectreference._classname__variablename)

In [27]:
# We can access private members from outside by knowing a small internal working technique called Name Mangling.
print(t._Test__x) # internally __x will be converted to _Test__x, so we can use it directly from outside.

10


In [28]:
t._Test__m1() # Accessing private method from outside the class using Name Mangling concept.

It is Private Method


### Protected Members

Protected attributes can be accessed within the class anywhere but from outside of the class only in child classes. We can specify an attribute as protected by prefexing with one _ symbol.<br>
**Syntax:** _variablename = value <br>
**Eg:** _name='durga'<br><br>

But it is just naming convention and it is not implemented in python, may be for the future versions purpose.

In [31]:
class Test:
    def __init__(self):
        self._x = 10
    def m1(self):
        print(self._x)
        
class SubTest(Test):
    def m2(self):
        print(self._x)
        
t=SubTest()
t.m1()
t.m2()

10
10


# Data Hiding

Outside person should not access data directly or our internal data should not go out directly. This concept is called **Data Hiding**<br><br>This OOP feature is nothing but data hiding.<br><br>
By declaring data members as private, we can implement **Data Hiding**.

In [32]:
class Account:
    def __init__(self,initial_balance):
        self.balance = initial_balance
        
a=Account(10000)
print(a.balance)

10000


Above code is not a good practice because, any out side person can directly access the account balance. We need some authentication to display the data in the account.<br><br>

In [34]:
class Account:
    def __init__(self,initial_balance):
        self.__balance = initial_balance # Balance is privatized so it can't be accessed from outside directly
        
a=Account(10000)
print(a.__balance) # Error will be raised as we are trying to access private member.

AttributeError: 'Account' object has no attribute '__balance'

In [35]:
class Account:
    def __init__(self,initial_balance):
        self.__balance = initial_balance # Balance is privatized so it can't be accessed from outside directly
    def getBalance(self):
        # we can write the validation or authentication code in this method.
        # if the person is valid, can display balance otherwise not
        return self.__balance
    
a=Account(10000)
#print(a.__balance)
print(a.getBalance()) # Accessing the data by calling the method.

10000


Security is the biggest advantage of Data Hiding.

# Abstraction

Abstraction is used to hide the internal functionality of the function from the users. The users only interact with the basic implementation of the function, but inner working is hidden. User is familiar with that "what function does" but they don't know "how it does."<br><br>

Hiding Internal Implementation and just highlight the set of services is the concept of Abstraction<br><br>

**Example 1:** Through Bank ATM GUI Screen,Bank people are highlighting the set of services what they are offering like cash withdrawl, balance enquiry etc  without highlighting internal implementation. This is nothing but Abstraction<br><br>

**Example 2:** In simple words, we all use the smartphone and very much familiar with its functions such as camera, voice-recorder, call-dialing, etc., but we don't know how these operations are happening in the background. Let's take another example - When we use the TV remote to increase the volume. We don't know how pressing a key increases the volume of the TV. We only know to press the "+" button to increase the volume.<br><br>

**Why Abstraction is Important?**<br>
In Python, an abstraction is used to hide the irrelevant data/class in order to reduce the complexity. It also enhances the application efficiency. Next, we will learn how we can achieve abstraction using the Python program.<br><br>

**Advantages of Abstraction:**<br>
1) **Security**: Internal implementation will not be revealed or displayed<br>
2) **Enhancement**: without effecting end user, we can perform any type of changes in the internal implementation.<br>
3) Maintainability and moduarity of the application will be very easy.<br>

In [2]:
from abc import ABC, abstractmethod   
class Car(ABC):   
    def mileage(self):   
        pass  
class Tesla(Car):   
    def mileage(self):   
        print("The mileage is 30kmph")   
class Suzuki(Car):   
    def mileage(self):   
        print("The mileage is 25kmph ")   
class Duster(Car):   
     def mileage(self):   
        print("The mileage is 24kmph ")   
class Renault(Car):   
    def mileage(self):   
        print("The mileage is 27kmph ")   
          
# Driver code   
t= Tesla ()   
t.mileage()   
  
r = Renault()   
r.mileage()   
  
s = Suzuki()   
s.mileage() 

d = Duster()   
d.mileage()  

The mileage is 30kmph
The mileage is 27kmph 
The mileage is 25kmph 
The mileage is 24kmph 


In the above code, we have imported the abc module to create the abstract base class. We created the Car class that inherited the ABC class and defined an abstract method named mileage(). We have then inherited the base class from the three different subclasses and implemented the abstract method differently. We created the objects to call the abstract method.

In [4]:
from abc import ABC  
  
class Polygon(ABC):   
  # abstract method
    def sides(self):   
        pass  

class Triangle(Polygon):   
    def sides(self):   
        print("Triangle has 3 sides")   

class Pentagon(Polygon):   
    def sides(self):   
        print("Pentagon has 5 sides")   

class Hexagon(Polygon):   
    def sides(self):   
        print("Hexagon has 6 sides")   

class square(Polygon):   
    def sides(self):   
        print("I have 4 sides")   

# Driver code   
t = Triangle()   
t.sides()   
  
s = square()   
s.sides()   
  
p = Pentagon()   
p.sides()   
  
k = Hexagon()   
k.sides()   

Triangle has 3 sides
I have 4 sides
Pentagon has 5 sides
Hexagon has 6 sides


In the above code, we have defined the abstract base class named Polygon and we also defined the abstract method. This base class inherited by the various subclasses. We implemented the abstract method in each subclass. We created the object of the subclasses and invoke the sides() method. The hidden implementations for the sides() method inside the each subclass comes into play. The abstract method sides() method, defined in the abstract class, is never invoked.

# Encapsulation

The process of binding/Grouping/encapsulating dat and corresponding behaviour(methods) into a single unit is nothing but **Encapsulation**.<br>
if any component follows data hiding and abstraction, such component is said to be encapsulated component.<br>
**Encapsulation = Data Hiding + Abstraction**<br><br>
Hiding data behind methods is the central conept of encapsulation.<br><br>
**Advantages of Encapsulation:**<br>
1) Security<br>
2) Enhancement will become easy<br>
3) Maintainability and moduarity of the application will be very easy.<br>
<br>
- The main advantage of encapsulation is Security.<br>
- The main limitation of encapsulation is it increases lenght of the code and slows down execution. we should compromise with performance.<br>
- If we want security we should compromise with performance.<br>
- If we want Performance we should compromise with security.

In [1]:
class Computer:

    def __init__(self):
        self.__maxprice = 900

    def sell(self):
        print("Selling Price: {}".format(self.__maxprice))

    def setMaxPrice(self, price):
        self.__maxprice = price

c = Computer()
c.sell()

# change the price
c.__maxprice = 1000
c.sell()

# using setter function
c.setMaxPrice(1000)
c.sell()

Selling Price: 900
Selling Price: 900
Selling Price: 1000


In the above program, we defined a **Computer** class.<br><br>

We used \_\_init\_\_() method to store the maximum selling price of Computer. We tried to modify the price. However, we can't change it because Python treats the \_\_maxprice as private attributes.<br><br>

As shown, to change the value, we have to use a setter function i.e setMaxPrice() which takes price as a parameter.

# 3 Pillars of OOPS

<img src="images/3pilllars_oops.png">

This is the complete story of Object Oriented Programming in Python. All the Major concepts are covered. 

# ========================= THE END =========================